src/Monolog/Handler/NativeMailerHandler.php
The message has not been updated after the copy/paste
=> Fix the exception message

src/Monolog/Handler/LogglyHandler.php
=> Added exception raised when a curl error occur in the Loggly handler

src/Monolog/Handler/RedisHandler.php
Updated RedisHandler constructor's docblock
=> Updated RedisHandler constructor's docblock

src/Monolog/Processor/MemoryUsageProcessor.php
Analog https://github.com/Seldaek/monolog/pull/594/files
=> Simplify MemoryUsageProcessor

src/Monolog/Handler/StreamHandler.php, tests/Monolog/Handler/StreamHandlerTest.php
=> stream handler creates a directory if its possible

doc/01-usage.md
After readme being split into parts, link needs to go to dedicated chapter
=> Fix link to seperate readme

src/Monolog/Handler/StreamHandler.php
Fix for https://github.com/Seldaek/monolog/issues/606.
=> Create directory on initial log write rather than class instantiation.

tests/Monolog/RegistryTest.php
=> Add more unit tests for Registry

src/Monolog/Handler/RavenHandler.php, tests/Monolog/Handler/RavenHandlerTest.php
It gives the ability to override how events are grouped together in Sentry
=> RavenHandler handles custom checksums

src/Monolog/Handler/RollbarHandler.php
Any thoughts @paulstatezny? Did you specifically exclude this data?
=> Allow extra_data and payload to be sent, too

src/Monolog/Handler/SwiftMailerHandler.php, tests/Monolog/Handler/SwiftMailerHandlerTest.php
Added generating unique id when building message and test.
=> SwiftMailerHandler bugfix

src/Monolog/Formatter/ChromePHPFormatter.php, src/Monolog/Handler/CubeHandler.php, src/Monolog/Handler/SlackHandler.php
* merge multiple isset/unset into sigle
* fix typo in variable name
* php annotations for throwable exceptions.
=> fix CubeHandler http connection and few small updates

src/Monolog/Formatter/NormalizerFormatter.php, tests/Monolog/Formatter/NormalizerFormatterTest.php
See issue at https://github.com/Seldaek/monolog/issues/673
=> #673 Fix fatal error while normalizing with __toString method

tests/Monolog/Handler/NativeMailerHandlerTest.php
=> add tests for NativeMailerHandler

tests/Monolog/Handler/PushoverHandlerTest.php
=> Remove excess parameter from createHandler

src/Monolog/Handler/RavenHandler.php, tests/Monolog/Handler/RavenHandlerTest.php
Raven client [fingerprint] (https://github.com/getsentry/raven-php/blob/master/docs/usage.rst#optional-attributes) support.
=> Raven client fingerprint support

src/Monolog/Handler/GroupHandler.php
Hello,
I would like to know if it's possible to add such shortcut for the `GroupHandler`?
Thanks,
=> Allow GroupHandler to set a formatter to all nested handlers

src/Monolog/Formatter/LogglyFormatter.php, tests/Monolog/Formatter/LogglyFormatterTest.php
Hi! This is a my first PR to Monolog :)
This PR removes de TODO in the LogglyFormatter, unseting the "datetime" parameter.
=> Unset the "datetime" parameter in LogglyFormatter

src/Monolog/Handler/AbstractHandler.php, src/Monolog/Handler/WhatFailureGroupHandler.php
=> Catch Throwable

src/Monolog/Formatter/NormalizerFormatter.php
Looks like these were TODOs for 2.0, so might as well get these out of the way.
=> Change out Exception to Throwable

src/Monolog/Handler/SendGridHandler.php
Send logs using SendGrid API v2
=> ADD support to SednGrid Handler

doc/02-handlers-formatters-processors.md, src/Monolog/Formatter/LogmaticFormatter.php, src/Monolog/Handler/LogmaticHandler.php, tests/Monolog/Formatter/LogmaticFormatterTest.php, tests/Monolog/Handler/LogmaticTest.php
Add Logmatic.io provider.
❤️ Monolog
=> Add Logmatic.io provider.

src/Monolog/Formatter/NormalizerFormatter.php, tests/Monolog/Formatter/NormalizerFormatterTest.php
SoapFault use dynamic properties to add informations.
This PR add these informations in normalizer.
=> Added informations to normalize a SoapFault

src/Monolog/Formatter/JsonFormatter.php, tests/Monolog/Formatter/JsonFormatterTest.php
#835 Better support for PHP7 \Throwable in JsonFormatter
=> Better support for PHP7 \Throwable

src/Monolog/Logger.php
Did you consider to build a complete API?
=> Declaring That a Logger Can Throw an Exception

src/Monolog/Formatter/MongoDBFormatter.php
Fixes: https://github.com/Seldaek/monolog/issues/883
=> Fixing date/time formatting in MongoDBFormatter

src/Monolog/Handler/RavenHandler.php
=> Add missed return phpdoc tag.

doc/message-structure.md
Addresses https://github.com/Seldaek/monolog/issues/516
=> Add documentation on internal log message structure

LICENSE
=> Happy 2017 Jordi / Seldaek / Monolog

src/Monolog/Formatter/JsonFormatter.php
I decide to add missing param for constructor PHPDoc. But did not sure because of missing PHPDoc in master.
=> Update JsonFormatter PHPDoc.

src/Monolog/ErrorHandler.php, src/Monolog/Handler/ChromePHPHandler.php, src/Monolog/Handler/PHPConsoleHandler.php, src/Monolog/Processor/WebProcessor.php
http://php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce
=> Use coalesce operator

src/Monolog/Formatter/LogstashFormatter.php, tests/Monolog/Formatter/LogstashFormatterTest.php
as mentioned in #913 just add the integer-value of level to an additional field in the log-message.
=> map loglevel (int-value) to log-message, as well

src/Monolog/Formatter/LogstashFormatter.php, tests/Monolog/Formatter/LogstashFormatterTest.php
Fixes #975.
I'll fix some other problems with this formatter after this PR gets merged.
=> LogstashFormatter: format context and extra fields as JSON objects

.travis.yml
refs: https://github.com/Seldaek/monolog/pull/997#issuecomment-379158443
=> Drop HHVM in .travis.yml

LICENSE
Happy 2018! Another year of perfect logging! :birthday:
=> Happy 2018 to Monolog

tests/Monolog/Handler/ErrorLogHandlerTest.php
Changed `testShouldNotAcceptAnInvalidTypeOnContructor`
=> Typo on method name

src/Monolog/Formatter/LogstashFormatter.php
Logstash has a new home and is also writte in java instead of ruby.
=> fix @see reference for logstash

src/Monolog/Logger.php, tests/Monolog/LoggerTest.php
Handlers, processors and formatters may rise exceptions while logging a record, and if the user does not wrap each Monolog calls with a try/catch, this will crash the entire app (#500). Using a WhatFailureGroupHandler seems to have [some downsides](https://github.com/Seldaek/monolog/issues/946).
So this pull request aims to keep Monolog's default behavior unchanged while allowing users to define their own default behavior through a callback, and for example turn Monolog exceptions to PHP Warnings, or change the HTTP response code.
=> Custom exception handler (#500)

src/Monolog/ErrorHandler.php
Resolves Seldaek/monolog#1096.
=> Set HTTP response code to 500 in case of exceptions

doc/02-handlers-formatters-processors.md
Updated docs to reflect the dependency of package graylog2/gelf-php in order to work
=> Update docs for GelfHandler

src/Monolog/Processor/PsrLogMessageProcessor.php, tests/Monolog/Processor/PsrLogMessageProcessorTest.php
Successor of #972 
Does two things:
- Include milliseconds in the default date format
- Show actual content of the array
=> Better PSR-3 message formatting

src/Monolog/Handler/FingersCrossed/ActivationStrategyInterface.php, src/Monolog/Handler/FingersCrossed/ChannelLevelActivationStrategy.php, src/Monolog/Handler/FingersCrossed/ErrorLevelActivationStrategy.php, src/Monolog/Handler/Slack/SlackRecord.php
Hey! 
Is this is the sort of thing you wanted help with for the 2.x milestone?
I'm more than happy to keep going through the handlers when I'm in boring meetings... Let me know if you'd rather have a separate PR for each handler or if you're ok with a bunch of them in one PR :)
And feel free to close this if it's not what you wanted and I'll go back to paying attention 😂.
=> Add scalar hints and return types to a few Handler classes

src/Monolog/Handler/TestHandler.php
Shouldn't the test handler be reset as well?
=> Reset test handler

src/Monolog/Formatter/NormalizerFormatter.php, tests/Monolog/Formatter/JsonFormatterTest.php, tests/Monolog/Formatter/NormalizerFormatterTest.php
=> Enable JSON encode pretty print

.travis.yml
give version 1.x some ❤️  as well... 😋
=> Add to travis PHP 7.3 for v1 also

src/Monolog/Formatter/HtmlFormatter.php, src/Monolog/Formatter/LineFormatter.php, src/Monolog/Formatter/LogstashFormatter.php, src/Monolog/Formatter/NormalizerFormatter.php, src/Monolog/Handler/BufferHandler.php, src/Monolog/Handler/ProcessHandler.php, src/Monolog/Handler/ProcessableHandlerInterface.php, src/Monolog/Handler/PsrHandler.php, src/Monolog/Handler/PushoverHandler.php, src/Monolog/Handler/RavenHandler.php, src/Monolog/Handler/RotatingFileHandler.php, src/Monolog/Handler/Slack/SlackRecord.php, src/Monolog/Logger.php, src/Monolog/Processor/GitProcessor.php, src/Monolog/Processor/IntrospectionProcessor.php, src/Monolog/Processor/MercurialProcessor.php, src/Monolog/Processor/PsrLogMessageProcessor.php, src/Monolog/Processor/UidProcessor.php, src/Monolog/Processor/WebProcessor.php, src/Monolog/ResettableInterface.php, tests/Monolog/Handler/PHPConsoleHandlerTest.php, tests/Monolog/Handler/RollbarHandlerTest.php, tests/Monolog/Handler/SwiftMailerHandlerTest.php
As WIP to see if I will find more...
=> Docblock fixes

src/Monolog/SignalHandler.php
Credit goes to @gmponos for reporting the problem.
=> Fix the property for restarting syscalls (#1251)

src/Monolog/Handler/DeduplicationHandler.php
=> Check file was opened successfully before trying to read/write

src/Monolog/Handler/LogglyHandler.php
This change caches the curl handlers for every endoint and reuses them. This makes the logglyHandler two to three times faster.
=> Adding curl sharing to fix #1313

README.md
SilverStripe ^4.0 and future 5.x ship with monolog out of the box
=> Add SilverStripe as a framework integration to readme

doc/02-handlers-formatters-processors.md
=> Delete SlackbotHandler from docs

src/Monolog/Handler/Slack/SlackRecord.php
Fixes docblock, minor formatting tweak for readbility, and adds a new docblock for getSlackData record.
=> Readability updates

tests/Monolog/Handler/BufferHandlerTest.php, tests/Monolog/Handler/FingersCrossedHandlerTest.php, tests/Monolog/Handler/GroupHandlerTest.php, tests/Monolog/Handler/WhatFailureGroupHandlerTest.php
=> Use assertCount not assertTrue(count())

src/Monolog/Handler/ZendMonitorHandler.php, tests/Monolog/Handler/ZendMonitorHandlerTest.php
=> Compatibility with actively maintained versions of Zend Server

src/Monolog/Handler/InsightOpsHandler.php
I'm sorry copy/paste issue ¯\\\_(ツ)_/¯
I can fix it in 1.x as well.
=> Update exception message in InsightOpsHandler

tests/Monolog/Handler/ProcessHandlerTest.php
=> Fix testWriteOpensProcessAndWritesToStdInOfProcess

src/Monolog/Handler/FilterHandler.php, tests/Monolog/Handler/FilterHandlerTest.php
This fixes https://github.com/Seldaek/monolog/issues/1401
=> FilterHandler: fix handle empty batch of filtered records

.travis.yml
=> [2.x] Tweaked travis config

src/Monolog/Processor/GitProcessor.php
=> Check that  is not null before calling preg_match

src/Monolog/Handler/StreamHandler.php
Reword exception message to be more clear and to fix grammatical error
=> Fix grammatical error

src/Monolog/ErrorHandler.php, src/Monolog/Handler/FilterHandler.php, src/Monolog/Handler/FingersCrossedHandler.php, src/Monolog/Handler/MandrillHandler.php, src/Monolog/Handler/SamplingHandler.php, src/Monolog/Handler/SwiftMailerHandler.php, src/Monolog/Handler/TestHandler.php, src/Monolog/Logger.php
Based on 
https://github.com/fab2s/call_user_func
and 
https://github.com/symfony/symfony/pull/29309
thanks @fab2s
=> Replace call_user_func

src/Monolog/Handler/TelegramBotHandler.php
Added `handleBatch` method and fixed `write` method for `TelegramBotHandler`.
This is necessary to work with `BufferHandler`, `OverflowHandler`, etc.
=> Added support for working with BufferHandler

doc/02-handlers-formatters-processors.md
As found in https://github.com/Seldaek/monolog/pull/1504#discussion_r501172073.
=> chore(doc:formatters): fix typo

src/Monolog/Processor/PsrLogMessageProcessor.php, tests/Monolog/Processor/PsrLogMessageProcessorTest.php
=> Backport PsrLogMessageProcessor from master (2.x)

src/Monolog/Handler/StreamHandler.php
This change ensures atomic log record writing to the output stream.
=> Set StreamHandler stream chunk size, fixes #1552

src/Monolog/Formatter/LineFormatter.php, src/Monolog/Handler/BrowserConsoleHandler.php, src/Monolog/Handler/ErrorLogHandler.php, src/Monolog/Handler/SyslogUdpHandler.php, src/Monolog/Utils.php, tests/Monolog/UtilsTest.php
=> Fixes php8 non-backward compatible changes

README.md
An alternative and more complex solution for Nette framework
=> Add Nette integration to the README

.github/workflows/continuous-integration.yml, composer.json
#1587 enabled psr/log 2, but let's not stop there. 🚀
=> Allow psr/log 3

composer.json
`php-amqplib/php-amqplib` has released v3 https://github.com/php-amqplib/php-amqplib/releases
=> Allow php-amqplib/php-amqplib v3

composer.json
Closes https://github.com/Seldaek/monolog/issues/1596
=> Fix the composer.json

doc/01-usage.md
Fixes #889 
The idea behind this pull request is to put a little bit more light and understanding on the "Customizing log format" section of the help.
Not only mentioned in the issue referenced here but also happened to some colleges too.
Hopefully is good enough.
Ideas and suggestions are welcome too.
=> Documentation. Enrich documentation on "Customizing log format".

README.md
The addition of a new framework.
Magento comes out of the box with Monolog.
=> Addition of a new framework

src/Monolog/Processor/WebProcessor.php
Adding `user_agent` in the `WebProcessor` will be a good to have data point.
=> Added user_agent to the WebProcessor

src/Monolog/Formatter/JsonFormatter.php, src/Monolog/Formatter/NormalizerFormatter.php
Hello, 
This PR adds a configuration for max serialization depth (https://github.com/Seldaek/monolog/issues/924)
Thanks
=> Max depth formatter

src/Monolog/Handler/AmqpHandler.php
One of content_type, content_encoding, message_id, user_id, app_id, delivery_mode, priority, timestamp, expiration, type or reply_to, headers.
=> Add the ability to set or redefine attributes for messages in Rabbit.

src/Monolog/Handler/AmqpHandler.php
One of content_type, content_encoding, message_id, user_id, app_id, delivery_mode, priority, timestamp, expiration, type or reply_to, headers.
=> Add the ability to set or redefine attributes for AMQPMessage.

phpunit.xml.dist
This PR wants to update the config for phpunit to the format of the 9.x version to avoid the deprecation message
=> change config for PHPUnit

src/Monolog/Formatter/ElasticaFormatter.php, src/Monolog/Formatter/ElasticsearchFormatter.php, src/Monolog/Formatter/FluentdFormatter.php, src/Monolog/Formatter/GelfMessageFormatter.php, src/Monolog/Formatter/HtmlFormatter.php, src/Monolog/Formatter/JsonFormatter.php, src/Monolog/Formatter/LineFormatter.php, src/Monolog/Formatter/LogstashFormatter.php, src/Monolog/Formatter/NormalizerFormatter.php, src/Monolog/Formatter/WildfireFormatter.php, src/Monolog/Handler/ChromePHPHandler.php, src/Monolog/Handler/ErrorLogHandler.php, src/Monolog/Handler/FleepHookHandler.php, src/Monolog/Handler/GroupHandler.php, src/Monolog/Handler/IFTTTHandler.php, src/Monolog/Handler/MandrillHandler.php, src/Monolog/Handler/SendGridHandler.php, src/Monolog/Handler/SlackWebhookHandler.php, src/Monolog/Handler/SyslogUdpHandler.php, src/Monolog/Handler/TelegramBotHandler.php
In some constructors Exceptions are thown, but not mentioned in the Docblocks. This results in phpstan error messages when I want to catch these Exceptions.
=> add some @throws in constructors

src/Monolog/Handler/WhatFailureGroupHandler.php
=> WhatFailureGroupHandler catches failures in method close

src/Monolog/Handler/FingersCrossedHandler.php, tests/Monolog/Handler/FingersCrossedHandlerTest.php
Fixes https://github.com/Seldaek/monolog/issues/1800
=> FingersCrossedHandler fix passthruLevel checking (Fixes #1800)

src/Monolog/ErrorHandler.php, src/Monolog/Formatter/JsonFormatter.php, src/Monolog/Formatter/LineFormatter.php, src/Monolog/Formatter/LogmaticFormatter.php, src/Monolog/Formatter/MongoDBFormatter.php, src/Monolog/Formatter/NormalizerFormatter.php, src/Monolog/Handler/AbstractHandler.php, src/Monolog/Handler/FilterHandler.php, src/Monolog/Handler/LogglyHandler.php, src/Monolog/Handler/NativeMailerHandler.php, src/Monolog/Handler/PushoverHandler.php, src/Monolog/Handler/RotatingFileHandler.php, src/Monolog/Handler/Slack/SlackRecord.php, src/Monolog/Handler/SlackHandler.php, src/Monolog/Handler/SocketHandler.php, src/Monolog/Handler/SyslogUdpHandler.php, src/Monolog/Handler/TelegramBotHandler.php, src/Monolog/Logger.php, src/Monolog/Processor/TagProcessor.php, src/Monolog/Processor/WebProcessor.php
Spotted while preparing https://github.com/Seldaek/monolog/pull/1827
=> Use `@return $this` where applicable

src/Monolog/Handler/BufferHandler.php, tests/Monolog/Handler/BufferHandlerTest.php
Hello,
this is to address #1943 - pretty straightforward.
Also, can be easily backported to 2.x - please let me know if I should open another PR for 2.x branch
=> added possibility to set child handler after instantiation
