- tests/Monolog/Handler/GelfHandlerLegacyTest.php
- tests/Monolog/Handler/GelfMocks.php
Was previously broken by a coding standard commit 392ef35fd470638e08d0160d6b1cbab63cb23174 that removed some mock files necessary to execute the tests when graylog2/gelf-php is deleted and mlehner/gelf-php is installed instead. This is hidden from normal test suite runs because the tests are skipped when mlehner/gelf-php is not installed.
You can check that this wasn't working against the master branch by doing the following:
$ composer require --dev mlehner/gelf-php
$ rm -rfd vendor/graylog2
$ vendor/bin/phpunit
I was working on another contribution and wondered why so many tests were skipped in the Monolog test suite. I found this issue after digging into a few of the skips.
I'm not 100% sure on the history of the mlehner/gelf-php and graylog2/gelf-php packages, but the tests showed …
> Restore ability to continue using mlehner/gelf-php in test

- README.mdown
Hi, I've made an integration of Monolog into [Nette Framework](http://nette.org/en/) which has [reasonably big userbase](https://packagist.org/packages/nette/) and is the most popular PHP framework in Czech Republic.
> Nette Framework integration

- src/Monolog/Handler/SlackHandler.php
Adds the context items to Slack attachments.
```
$handler->addError('Foo', array('foo' => 'bar'));
```
> #493 Include context in slack extra info.

- src/Monolog/Handler/RavenHandler.php
- tests/Monolog/Handler/RavenHandlerTest.php
Its not currently possible to set user context in RavenHandler (for getsentry.com), this PR adds the functionality and related test.
> Added overwriting of user context to RavenHandler

- src/Monolog/Handler/LogEntriesHandler.php
It's preferable to be using data.logentries.com when sending Token Based logs.
Also it's nicer if we use port 443 since it is more then likely going to be open compared to port 20000 in environments.
> Use data.logentries.com and port 443 instead of api

- src/Monolog/Handler/NativeMailerHandler.php
PHP's mail() function accepts an optional additional_parameters argument which can be used to provide additional information, such as setting the envelope sender, for some MTAs.  This patch allows the NativeMailerHandler to pass these through.
> Allow passing additional parameters to PHP's mail().

- src/Monolog/Handler/NativeMailerHandler.php
NativeMailerHandler::setContentType() and NativeMailerHandler::setEncoding() both return the NativeMailerHandler object, allowing a fluent coding style.  This fix adds the same behaviour to NativeMailerHandler::addHeader() for so that all public non-inherited methods behave this way for consistency.
> Return self from NativeMailerHandler::addHeader().

- composer.json
- src/Monolog/Handler/SwiftMailerHandler.php
- tests/Monolog/Handler/SwiftMailerHandlerTest.php
This is an alternate implementation of #497 that not only allows customization of Swift_Message based on logged data, but also adds a performance gain when using the Swift_Message callback option. There is one possible BC break for anyone extending SwiftMailerHandler. See the bottom of this PR.
New test cases exercise SwiftMailerHandler using real instances of Swift_Message.
Prior to this PR a `SwiftMailerHandler` subclass had to override the entire `send()` method to customize the sent Swift_Message. After this PR subclasses can instead override the `buildMessage()` function. This was originally proposed in #497 and the implementation here is mostly the same.
Customizing the sent Swift_Message in a subclass:
```php
class CustomSwiftMailerHandler extends SwiftMailerHandler
{
protected …
```
> Make Swift_Message more easily customizable and lazy when sending email

- src/Monolog/Handler/TestHandler.php
- tests/Monolog/Handler/TestHandlerTest.php
These methods allow for writing tests with partial log matches. For example:
```php
$this->assertTrue(
$this->logHandler->hasErrorThatContains('The connection to the server has failed')
);
$this->assertTrue(
$this->logHandler->hasErrorThatContains('status 500')
);
```
> Add strpos based TestHandler methods

- src/Monolog/Formatter/LineFormatter.php
After profile code with XHProf, i find a many uses for LineFormatter::replaceNewLines. After replace calls strtr to str_replace, called time is halved.
With use strtr: http://prntscr.com/6tycs1
With use str_replace: http://prntscr.com/6tycw8
Script:
```php
$replaceTime = 0;
$trTime = 0;
$line = "This is a testing line for benchmarking:\nstrtr vs str_replace\r\nSecond line\nThird line";
for ($i = 0; $i < 10000; $i++) {
$time = microtime(true);
$newLine = str_replace(["\r\n", "\n"], '', $line);
$replaceTime += microtime(true) - $time;
$time = microtime(true);
$newLine = strtr($line, ["\r\n" => ' ', "\n" => ' ']);
$trTime += microtime(true) - $time;
}
print sprintf(
"Replace: %f\nStrtr: %s\n",
$replaceTime,
$trTime
);
```
Thank.
> Optimize replace new lines for LineFormatter

- README.mdown
- composer.json
- src/Monolog/Handler/PHPConsoleHandler.php
- tests/Monolog/Handler/PHPConsoleHandlerTest.php
There is a [PHPConsoleHandler](https://github.com/barbushin/monolog/blob/php-console-handler/src/Monolog/Handler/PHPConsoleHandler.php) that integrates Monolog with very popular Google Chrome extension [PHP Console](https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef) and its server library [php-console](https://github.com/barbushin/php-console). 
There is also [PHPConsoleHandlerTest](https://github.com/barbushin/monolog/blob/php-console-handler/tests/Monolog/Handler/PHPConsoleHandlerTest.php) with 25 tests  that are passed on PHP 5.3, 5.4 and 5.5.
I keep code style compatible with PSR1/2 and added documentation notes.
Referenced to #416
> Add PHPConsoleHandler to debug in Google Chrome

- src/Monolog/Handler/PushoverHandler.php
This change allows you to use the "formatted" message from your formatter.  This is helpful if you want to create a formatter that would include *some* context information beyond the message itself.
Since the default `LineFormatter` would be too verbose, I added a `useFormattedMessage()` method that accepts a boolean and would turn the use of the formatter on or off. This way, if you want to use a custom formatter, you can enable the functionality explicitly...but it will still work the same out of the box otherwise with just the message getting sent to Pushover.
> Allow use of formatted message in PushoverHandler

- README.mdown
Added Lumen, because why not.
Signed-off-by: Jeroen v.d. Gulik <jeroen@isset.nl>
> Added Lumen to list of supported frameworks

- src/Monolog/Logger.php
- tests/Monolog/LoggerTest.php
This is a rather small change, but keeping things DRY is always a good thing.
I removed the duplicated logic and replaced it with a `Monolog\Logger::toMonologLevel()` call.
Plus added the tests that cover that method.
> Removed a small code duplication, and added Logger::toMonologLevel() tests.

- tests/Monolog/Handler/CouchDBHandlerTest.php
This makes it more obvious that this test is not actually doing much
> Remove dead varialble

- src/Monolog/Logger.php
Added self-referenced returns to get fluent interfaces for `Monolog\Logger::pushProcessor` and `Monolog\Logger::pushHandler`
For more information, look at the [comment in this file](https://github.com/LoggerEssentials/LoggerEssentials/blob/3e17d9807d0f83cebd0ea183cb43c45c904f8347/docs/index.md#combine-with-monolog).
> Added self-referenced returns to get fluent interfaces

- src/Monolog/Logger.php
- tests/Monolog/LoggerTest.php
Add a setter method to allow changing the timezone used when creating
new log records. This provides a means to correct a behavioral change
introduced by 6cbdc04 where use of the PHP runtime default timezone
provided by `date_default_timezone_get()` was introduced. In most
environments the new default behavior is preferable, but if an
application allows the default timezone to vary between requests it
causes confusing log output.
> Add Logger::setTimezone()

- src/Monolog/Handler/RavenHandler.php
- tests/Monolog/Handler/MockRavenClient.php
- tests/Monolog/Handler/RavenHandlerTest.php
as discussed in c1fd9cddf2f2d4f49dc56cb647681ee086c6fca3, the `$this->ravenClient->user_context(null)` was too destructive in a hybrid use case. This PR fixes it. 
Changes made:
* changed logic from "reset first" into a "reset if user context exists"
* added assertions that verify newly discovered use cases won't break
* used single quotes for strings
> made raven user context less destructive

- src/Monolog/Handler/SlackHandler.php
Now it is impossible to add additional data fields to Slack request without copying large pieces of code or without dirty hacks. Fixing this.
> Making SlackHandler more extendable

- composer.json
RavenHandler uses Raven_Client::user_context(). This method is available since 0.8.0.
see https://github.com/getsentry/raven-php/commit/7dd1fb3a353eb2b456336a996e5265fc5756a085
> Fix: Wrong raven/raven version

- src/Monolog/Handler/HipChatHandler.php
- tests/Monolog/Handler/HipChatHandlerTest.php
Adds support for Hipchat's V2 API by way of setting the version flag.  V1 paths
should remain unchanged, and v1 remains the default for BC.
I have no way of testing V1 at this time, can someone pull this down to verify that still works?
> Add Hipchat V2 support

- src/Monolog/Handler/TestHandler.php
- tests/Monolog/Handler/TestHandlerTest.php
A couple of improvements to `Monolog\Handler\TestHandler`:
* DRY up record searching into a predicate-based method: `hasRecordThatPasses($predicate, $level)`
* DRY up boilerplate methods with magic `__call()`: e.g. `hasInfoThatContains($message)` => `hasRecordThatContains($message, Logger::INFO)`
* Add `@method` annotations for the pseudo-methods
* Add a Regular Expression matcher for records: `hasRecordThatMatches($regex, $level)`
* Add tests for the above
> TestHandler improvements

- src/Monolog/Handler/BrowserConsoleHandler.php
Up to now, BrowserConsoleHandler only shows output when output header is text/html. However many of our applications also use application/javascript (and obsolete text/javascript). With this PR, generated javascript will also be returned, but without the script tags.
> Add support for Javascript output in BrowserConsoleHandler

- src/Monolog/Handler/RedisHandler.php
- tests/Monolog/Handler/RedisHandlerTest.php
100% backward compatible, defaults to not capping collection size.
Additional constructor param of $capSize added which will ensure logs
list is treated as a FILO queue
Test coverage on new functionality
> Adds ability to cap log size in redis

- src/Monolog/Handler/CubeHandler.php
> Fix: Use FQCNs for exceptions in docblock, too

- src/Monolog/Handler/SocketHandler.php
> Fix: Type should be bool

- src/Monolog/Processor/IntrospectionProcessor.php
Ensure the Monolog namespace is always ignored, and doesn't have to be defined in use.
> Prevent Monolog from ever being introspected

- src/Monolog/Processor/IntrospectionProcessor.php
Helps make this compliant where there is no class defined
> Ignore "call_user_func" from debug backtrace

- src/Monolog/Handler/IFTTTHandler.php
I've added a fairly simple handler that allows you to trigger Maker actions on IFTTT.
The great thing about IFTTT is, you can essentially do anything you want with the logs, for free:
- You want to get a text alert when there's a database error? Yep.
- You want to create a GitHub issue when there's a critical error? Yep.
- You want your house to go lockdown mode and start blinking red lights when there's an emergency logged? Sure. 
On a more serious note though, how should the tests be handled for this? I looked through the other handlers that use cURL, such as Mandrill and Loggly, and they don't seem to have tests, so I didn't add one to this. **However**, if you do want one, should I just mock a cURL object? Or would you prefer I do something else?
> Added IFTTT Handler

- src/Monolog/Logger.php
- tests/Monolog/LoggerTest.php
Logger::setHandlers() is intended to help dependency injection systems that deal more elegantly with property setters than constructor arguments. Alongside getHandlers(), pushHandler(), popHandler(), it is
a logical addition to the API. 
More controversially. It also attempts to address some possible errors in the format of the data passed:
- If a map is passed, the keys are removed, as these aren’t expected
by Monolog
- If falsey values are included, these are stripped
It relies on Logger::pushHandler() internally, so that if any special behaviour is added in the future, this only needs to be added in one place.
Does anyone else benefit from this facility?
> Added Logger::setHandlers()

- src/Monolog/Processor/IntrospectionProcessor.php
Recent merge of #608 misses check whether the trace exists at all at the specific index, leading to undefined offset.
```
E_NOTICE: Undefined offset: 3
```
And because the while statement became unreadable (and too long), I moved it into a separate method.
> FIX IntrospectionProcessor: E_NOTICE

- composer.json
- src/Monolog/Handler/RavenHandler.php
- tests/Monolog/Handler/RavenHandlerTest.php
refactored RavenHandler a bit to support many additional parameters, not only `checksum` but also (added in 0.11) `release` parameter
ref: https://github.com/getsentry/raven-php/blob/master/CHANGES
`release` allows to track the version of an application that the logs came from
> RavenHandler supports extra parameters

- src/Monolog/Processor/UidProcessor.php
- tests/Monolog/Processor/UidProcessorTest.php
Would be nice to have an easy way to get Uid from UidProcessor. I have a scenario where I want to pass a parent's Uid to children processes for log grouping.
> Add getUid() to UidProcessor

- src/Monolog/Handler/SlackHandler.php
According to slack documentation (https://api.slack.com/docs/attachments),  an attachment may have a title and a text. The log message and title should use these fields. One of the benefits of using these two properties instead of adding a field is that it's shortened (with a "show more" button) and expandable by slack. It adds a bit of hierarchy in the attachement. Message is the content. Extra and context are additional fields.
> Use `text` and `title` fields for SlackHandler

- .travis.yml
- composer.json
Protect against syntax compatibility issues such as the non-5.3
compatible array syntax corrected in 5785a9a by running a linter during
Travis CI testing for pull requests.
> Add linting to Travis tests

- src/Monolog/Processor/IntrospectionProcessor.php
Since the code does not need neither the 'object' not 'args' keys from backtrace, we can save some memory by not requesting them.
I have a better idea planned too: first attempt getting the trace with limited back trace (limit to only about 5 results), and get the full one only if those were not enough
> Reduce memory consumption of the debug_backtrace call

- src/Monolog/Handler/GelfHandler.php
This replaces a double-quote occurrence with
a single-quote one to comply with the CGL
as well as fixing an escaping mistake.
> [TASK] CGL fix

- src/Monolog/Logger.php
- tests/Monolog/LoggerTest.php
Introduce a new `useMicrosecondTimestamps()` static method to Logger
that allows runtime selection of whether or not to create microsecond
resolution timestamps for log records.
Generating microsecond resolution timestamps by calling
`microtime(true)`, formatting the result via `sprintf()` and then
parsing the resulting string via `DateTime::createFromFormat` can incur
a measurable runtime overhead vs simple usage of `new DateTime` to
capture a second resolution timestamp in systems which generate a large
number of log events.
The default behavior of generating high precision timestamps remains the
same, but may be changed in a future release. Users requiring high
precision timestamps are encouraged to explicitly call
`Monolog\Logger::useMicrosecondTimestamps(true)` in their setup code. …
> Optionally reduce timestamp resolution for performance

- src/Monolog/Handler/SocketHandler.php
- tests/Monolog/Handler/SocketHandlerTest.php
greater than writingTimeout settings.
When a remote socket is closed without the FIN packet, it may be that the local socket is not closed but the data is not sent anymore so php entering in an infinite loop.
To reproduce the issue you can:
- start netcat in listening mode on 1234 port:
`nc -l 1234`
- run the script locateted here: https://gist.github.com/silvadanilo/5043fc2d16b5346b1db1
- after a few logs entry, interrupt netcat with Ctrl+c
> Avoid infinite loops when no data is written on a socket for a time 

- src/Monolog/Formatter/FluentdFormatter.php
- tests/Monolog/Formatter/FluentdFormatterTest.php
Serializes a log message to Fluentd unix socket protocol.
Fluentd config:
```
<source>
type unix
path /var/run/td-agent/td-agent.sock
</source>
```
Monolog setup:
```php
$logger = new Monolog\Logger('fluent.tag');
$fluentHandler = new Monolog\Handler\SocketHandler('unix:///var/run/td-agent/td-agent.sock');
$fluentHandler->setFormatter(new Monolog\Formatter\FluentdFormatter());
$logger->pushHandler($fluentHandler);
```
> Add fluentd formatter.

- src/Monolog/Handler/HipChatHandler.php
- tests/Monolog/Handler/HipChatHandlerTest.php
Although the docs for API version v2 are very sparse, a quick test confirmed, that the name should always be sent:
Without the patch:
With the patch (sorry for obfuscation, client name...):
(same config)
> [HipChatHandler] Always send the "from" name

- src/Monolog/Formatter/NormalizerFormatter.php
- tests/Monolog/Formatter/LogstashFormatterTest.php
- tests/Monolog/Formatter/NormalizerFormatterTest.php
Detect and attempt to recover from json_encode errors triggered by
strings containing invalid UTF-8 sequences. Recovery will only be
attempted when encoding strings or arrays. If recovery fails then
a RuntimeException will be thrown.
The recovery process will convert invalid UTF-8 codepoints as though the
input string was encoded using the ISO-8859-15 character encoding. This
conversion may result in incorrect string output if the original
encoding was not ISO-8859-15, but it will be a valid UTF-8 string.
Closes #545 and possibly #616
> Attempt to recover from json encoding errors

- src/Monolog/Logger.php
Changed iterating over the $handlers array to allow for correct sequential processing regardless of array containing indexed numerical keys, or associative string keys in the array.
It iterates over the entire array until it finds the $handlerKey that was identified earlier using isHandling(). Once the starting position is found it will execute handle() on each handler unless a handler returns true indicating the handler completed the processing of the record, bubbling to the next handler should not occur, and the loop breaks.
This fixes an issue where an associative array of handlers is passed into the Logger constructor when instantiated.
magento/magento2#2529
Seldaek/monolog#691
> Logger iterating over an associate array of handlers

- src/Monolog/Formatter/HtmlFormatter.php
- src/Monolog/Formatter/LineFormatter.php
- src/Monolog/Formatter/NormalizerFormatter.php
- tests/Monolog/Formatter/LogstashFormatterTest.php
- tests/Monolog/Formatter/NormalizerFormatterTest.php
- tests/Monolog/Formatter/ScalarFormatterTest.php
Fixed todo from #197 
> Check all PHP_VERSION and version_compare checks for relevance
> Removed unnecessary php version checks after php dependency bump to 7.0

- src/Monolog/Handler/RavenHandler.php
- tests/Monolog/Handler/RavenHandlerTest.php
This adds an internal release number to the raven handler. The release
number is added to what is sent to sentry unless something already is
present because a release number was sent via "context" or "extra".
An abstraction might be introduced somewhere to represent release number generators, so that different generators might be implemented, but I am not sure where, and I am also unsure whether such a class should be injected instead of the release number. In short, should it work like this : 
```
$releaseNumberGenerator = new GitDescribeReleaseNumberGenerator();
$ravenHandler->setRelease($releaseNumberGenerator->generate());
```
or like this : 
```
$ravenHandler->setReleaseGenerator($releaseNumberGenerator);
// the handler calls generate() internally
```
or if both things should be …
> add release number to every log

- src/Monolog/Formatter/JsonFormatter.php
- tests/Monolog/Formatter/JsonFormatterTest.php
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |
> Add ability to include exception's stack traces in `Monolog\Formatter\JsonFormatter`

- src/Monolog/Handler/SlackHandler.php
We don't need LineFormatter when not configured to use short attachment.
I think current tests will be enough to cover this behavior.
> Instantiate LineFormatter only when configured to use short attachment

- src/Monolog/Handler/AmqpHandler.php
- tests/Monolog/Handler/AmqpHandlerTest.php
If use the AmqpHandler with the php-ext amqp, the content type is `plain/text` for each message in the queue because the property name is wrong written.
This pull request, change the property name `Content-type` by correct property name `content_type`.
The patch work fine with RabbitMQ.
> Fix content_type for AMQP Message

- composer.json
videlalvaro/php-amqplib has been abandoned in favor of
php-amqplib/php-amqplib
Related : #744
> use maintained package reference in suggestion

- src/Monolog/Handler/SocketHandler.php
This property is used, but not declared, in writingIsTimedOut
Don't know why it pass on travis, but locally I got
1) Monolog\Handler\SocketHandlerTest::testAvoidInfiniteLoopWhenNoDataIsWrittenForAWritingTimeoutSeconds
Undefined property: Mock_SocketHandler_4c030aea::$lastWritingAt
This trivial fix fix this
> missing property

- .travis.yml
ext-mongo does not exist for PHP 7 either, not only for HHVM.
> Only load mongo.so for PHP 5.x on Travis

- src/Monolog/Handler/ChromePHPHandler.php
This will make it possible to reuse the regular expression in handlers that wrap or extend this one (see symfony/symfony#18439 for a use case).
> extract browser detection regex into a constant

- tests/Monolog/Formatter/GelfMessageFormatterTest.php
Version 1.4.1 is the last version compatible with PHP < 5.3.9, but
filtered all message attributes with zero string length.
> fix Gelf message formatter tests

- src/Monolog/Handler/HandlerWrapper.php
According to the given example, $handler property should not be private.
> Fixed $handler property visibility in the HandlerWrapper

- src/Monolog/Handler/AmqpHandler.php
- tests/Monolog/Handler/AmqpHandlerTest.php
Fixed todo from #197
> Remove substr TODO in AmqpHandler
> Removed substr call in amqp routing key generator

- src/Monolog/Handler/FingersCrossedHandler.php
- tests/Monolog/Handler/FingersCrossedHandlerTest.php
This is useful if you have a FingersCrossedHandler set up and some where in your application are interested in all output regardless of whether the threshold is actually reached. For example to temporarily debug some problem. One can replace the handler in that spot, but this is signifcantly easier to use.
> Provide means to manually activate a FingersCrossedHandler

- src/Monolog/Handler/RotatingFileHandler.php
- tests/Monolog/Handler/RotatingFileHandlerTest.php
Add deprecation errors on RotatingFileHandler when attempting to set dateFormats of fileFormats that break the possibility of rotating easily in RotatingFileHandler. Version 2.x
of Monolog will throw `\InvalidArgumentException`s in these cases.
- Require the dateFormat to be one of three presets ('Y-m-d', 'Y-m' or 'Y') to
ensure that dates can be sorted lexographically
- Require the filenameFormat to contain the (sub)string `{date}` so we will
actually create new files instead of the same file over and over again.
Related to https://github.com/Seldaek/monolog/pull/773
> Add deprecation errors on RotatingFileHandler

- src/Monolog/Handler/RotatingFileHandler.php
- tests/Monolog/Handler/RotatingFileHandlerTest.php
- Require the dateFormat to be one of three presets ('Y-m-d', 'Y-m' or 'Y') to
ensure that dates can be sorted lexographically
- Require the filenameFormat to contain the (sub)string `{date}` so we will
actually create new files instead of the same file over and over again.
Fixes https://github.com/Seldaek/monolog/issues/771
This PR breaks BC in a major way so should be set for 2.0
If accepted, the checks added to `setFilenameFormat` could be added to the 1.x branch as well, but raise `E_USER_DEPRECATED` errors instead of throwing `InvalidArgumentException`s as @stof pointed out in https://github.com/Seldaek/monolog/issues/771
> Lock down RotateFileHandler to prevent errors with rotation

- doc/02-handlers-formatters-processors.md
- src/Monolog/Handler/ProcessHandler.php
- tests/Monolog/Handler/ProcessHandlerTest.php
This implements #452, I hope you find it useful.
**Some points/questions that I'd like to add here:**
1. I did intentionally not include an option to pass the already opened process to the handler for now, but rather require the consumer to pass a command. This is due to the circumstance that the `proc_open()` call has to be quite specific in order for the handler to work properly.
2. I am not entirely sure about the name. Although it was suggested in the linked issue, it might be true that "ProcessHandler" could cause some confusion, as there are classes like "ProcessableHandlerInterface" and "ProcessableHandlerTrait" in the codebase, which are unrelated. I could not think of anything better and therefore went with it for now, but please, suggestions are welcome!
3. Is there any …
> Created "ProcessHandler", that logs records to the STDIN of a process.

- src/Monolog/Handler/SocketHandler.php
Proposed change fixes `TypeError` thrown while calling [`stream_set_timeout()`](stream_set_timeout) which expects both 2nd and 3rd arguments to be integers while [`floor()`](https://secure.php.net/manual/en/function.floor.php) returns `float` / `bool` and [`round()`](https://secure.php.net/manual/en/function.round.php) returns `float` as well.
**Warning**: This may not be the best solution, I didn't go through internals of class in depth, but I've noticed this breaks Slack logging for us after updating to most recent commit so it may be useful for others too.
> Fix for TypeError within SocketHandler

- src/Monolog/Formatter/JsonFormatter.php
- src/Monolog/Formatter/NormalizerFormatter.php
- src/Monolog/Formatter/WildfireFormatter.php
- tests/Monolog/Formatter/NormalizerFormatterTest.php
This is an issue in particular when $GLOBALS gets stuck into $context. This is something Symfony's ErrorHandler does when an error is thrown in global scope. The result is infinite recusion resulting in stack overflow on normalize().
Currently only adds a failing test.
Options are
- Limit nesting, by introducing depth counting to `normalize()`
- Reference detection (more complicated and uses more memory)
> Normalization of arrays containing self references

- src/Monolog/Handler/RotatingFileHandler.php
- tests/Monolog/Handler/RotatingFileHandlerTest.php
Currently only dashes are allowed in date formats (i.e., "Y-m-d").
This commit also allows slashes, underscores and dots to be used instead
of only dashes for more flexibility.
> Allow alternative date separators for RotatingFileHandler

- src/Monolog/Handler/MandrillHandler.php
- src/Monolog/Handler/SendGridHandler.php
These two classes crash when I try to include them on PHP 7.
BTW: I found this issue using my new static analysis tool [PHPStan](https://github.com/phpstan/phpstan). I can send you a PR with integrating the tool in the Monolog build script.
> Fixed incompatible interfaces with MailHandler

- src/Monolog/Handler/RavenHandler.php
I think this is related to #759.
> Add support for PHP 7 errors in RavenHandler

- README.mdown
Hello everyone,
I'm working on a Yii 2 component to port Monolog. I edited the README file by adding the project, the first developed for this framework.
> Added Yii2 component on README.mdown

- README.mdown
Updated the minimum required PHP version in README from 5.3 to 7.0 as detailed in `composer.json`.
Fixes #873
> Minimum required PHP version in README

- tests/Monolog/Handler/MockRavenClient-gte-0-16-0.php
- tests/Monolog/Handler/RavenHandlerTest.php
From composer.json: `"sentry/sentry": "^0.13"`
Latest 0.x `sentry/sentry`: 0.22.0
sentry/sentry 0.16.0 changed the function signature of Raven_Client::capture():
0.16.0: `public function capture($data, $stack = null, $vars = null)`
0.15.0: `public function capture($data, $stack, $vars = null)`
While the test suite silently passes with PHP < 7.1, running the test suite with
PHP 7.1 fails with the following error:
`Declaration of Monolog\Handler\MockRavenClient::capture($data, $stack, $vars = NULL)
should be compatible with Raven_Client::capture($data, $stack = NULL, $vars = NULL)`
> Fix tests for sentry/sentry >= 0.16.0 (and < 1.0)

- src/Monolog/Handler/RavenHandler.php
- tests/Monolog/Handler/RavenHandlerTest.php
Recently in production, I received a lot of sentry notifications for `NotFoundHttpException`, which surprised me because we explicitly ignore 404 with a custom activation strategy.
After digging a little bit, I found out that the `NotFoundHttpException` was not the real reason to send the error to Sentry, but a previous error was, only the RavenHandler was not picking this one.
That lead me to believe that the `RavenHandler` should pick the first highest log message as the main one, which is the more likely to be the one who "triggered" things in the first place, rest becoming only a resultant of it.
Moreover, this is more consistent with how the `MailHandler` is behaving (https://github.com/Seldaek/monolog/blob/58544af7ff9d0c54ef36bc0e4e79330cda751b0e/src/Monolog/Handler/MailHandler.php#L …
> Make the RavenHandler picks the first highest record as main

- src/Monolog/Handler/SlackHandler.php
Wheter the output should include only the message without extradata.
It's related to issue #871
> SlackHandler, new parameter $printSimpleMessage

- src/Monolog/Formatter/LineFormatter.php
If variable in extra or context isn't defined, than placeholder will not not be replaced in format string. This patch remove all not replaced placeholders
> Remove substitution for not defined variables

- doc/02-handlers-formatters-processors.md
- src/Monolog/Handler/NoopHandler.php
- tests/Monolog/Handler/NoopHandlerTest.php
This handler handles anything, but does nothing, and does not stop bubbling to the rest of the stack, unlike the NullHandler.
This can be used for testing, or to disable a handler when overriding a configuration without influencing the rest of the stack.
The specific use-case I need this for is in symfony, where `config_test.yml` imports `config_dev.yml`, but needs to disable some handlers and add some others:
`config_dev.yml`:
```
monolog:
handlers:
stderr:
type:   stream
path:   "php://stderr"
level:  debug
```
`config_test.yml`:
```
imports:
- { resource: config_dev.yml }
monolog:
handlers:
test:
type:   test
level:  debug
stderr:
type:   'null'
```
This fails, because the `stderr` handler is first in the stack, even after overriding it. Because the NullHandler doesn't bubble, the …
> Added the NoopHandler.

- src/Monolog/Handler/SyslogUdp/UdpSocket.php
The socket resource can be closed, purged or lost during the runtime of an application.
It is valid concern, because the resource is acquired and used at different times during request.
LogicException is more for static preconditions that have to be valid before function call.
I realize that it's BC break, but it still makes sense. Having that I can handle all RuntimeExceptions the same way, instead of using catch-all Exception handling.
> Throw RuntimeException if socket resource is missing

- doc/02-handlers-formatters-processors.md
- src/Monolog/Handler/Slack/SlackRecord.php
- src/Monolog/Handler/SlackHandler.php
- src/Monolog/Handler/SlackWebhookHandler.php
- src/Monolog/Handler/SlackbotHandler.php
- tests/Monolog/Handler/Slack/SlackRecordTest.php
- tests/Monolog/Handler/SlackHandlerTest.php
- tests/Monolog/Handler/SlackWebhookHandlerTest.php
- tests/Monolog/Handler/SlackbotHandlerTest.php
See https://github.com/Seldaek/monolog/issues/743#issuecomment-242994019
This is keeping the previous `SlackHandler`, but extracts the message formatting logic and introduces two new Slack handlers:
- `SlackbotHandler` - this is the simplest way to log to Slack and most people could use that. It doesn't allow fancy formatting, but has autolinking and the simplest configuration with two clicks in the Slack settings and getting a token.
- `SlackWebhookHandler` - This is a bit more advanced as it allows for the same formatting and adding attachements as the `SlackHandler`, but it uses the Slack Webhooks which are quite easier to set up than the OAuth API. The minimum it requires is a webhook URL which is a retrievable with about two clicks in the Slack settings. Even the channel is optional …
> Add new Slack handlers using Slackbot and webhooks

- src/Monolog/Formatter/NormalizerFormatter.php
Iterators and Generators may not be rewindable, so foreach is not safe to use on them.
Iterators and especially Generators may trigger irreversible actions on calling next(), so iterating over all values can potentially cause harm, e.g. imagine an iterator over a set of HTTP POST requests that are sent when the next value is requested . The only sufficiently safe thing to iterate and include here are primitive arrays.
> Do not iterate non-array Traversables

- src/Monolog/Handler/Slack/SlackRecord.php
- src/Monolog/Handler/SlackHandler.php
- src/Monolog/Handler/SlackWebhookHandler.php
- tests/Monolog/Handler/Slack/SlackRecordTest.php
- tests/Monolog/Handler/SlackWebhookHandlerTest.php
While #846 was focused on providing the ability to communicate with Slack via webhooks/bot, there's a bunch of improvements that can be done before 2.x. Thanks to @greeny, @websirnik, @jewome62 and @mirfilip for ideas.
> Slack improvements

- doc/01-usage.md
- doc/04-extending.md
- doc/sockets.md
- src/Monolog/Handler/PHPConsoleHandler.php
- src/Monolog/Registry.php
Noticed some of the docs had code using `addInfo` which I had also noticed was removed in the recent upgrade, so I did some grepping and replaced mentions of it with `info` in some comments and documentation. I did this with the other add* methods as well.
> Replacing the add* methods in the docs and comments with the PSR-3 compliant methods

- CHANGELOG.md
- doc/01-usage.md
- src/Monolog/Formatter/NormalizerFormatter.php
patch contains some spelling fixes ( just in comments ) as found by a bot ( https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.
> spelling fixes (comments, text)

- tests/Monolog/ErrorHandlerTest.php
This will improve code coverage on `Monolog\ErrorHandler` class.
I left `ErrorHandler::register` not fully covered on purpose, since I got no easy way to test handlers methods.
Hope this helps. :)
> Improves code coverage

- src/Monolog/ErrorHandler.php
See this [PHP5.3 bug](https://bugs.php.net/bug.php?id=47987)
When an error is triggered on compile-time the autoloader is not called which create a "`LogLevel` class not found" error.
I make the ErrorHandler extend LogLevel so ErrorHandler will already have all the log level it's looking for, and the autoloader won't be called.
> Php5.3 autoload errors

- src/Monolog/Logger.php
I am micro-optimising one local project and have noticed that the
```php
$levelName = static::getLevelName($level);
```
inside the `Logger::addRecord()` can be moved slightly later so that it was not invoked when we don't need it (when there are no handlers for a given error level).
> Micro-optimisation: delayed unnecessary `static::getLevelName`

- README.md
"come out of the box" => "comes out of the box"
> Correcting a small spelling mistake in README.md.

- src/Monolog/Processor/PsrLogMessageProcessor.php
- tests/Monolog/Processor/PsrLogMessageProcessorTest.php
Adds support for DateTime objects being passed and formatted in PSRLogMessages.
Seems like it might be a good addition. Totally understand if this change pushes this processor beyond it's intended scope.
Cheers.
> Handle DateTime objects in formatted messages

- src/Monolog/Handler/SyslogUdpHandler.php
- tests/Monolog/Handler/SyslogUdpHandlerTest.php
This pull request adds ability to build correct rfc5424 syslog messages and resolves #942 . SyslogUdpHandler got extra "ident" field for its constructor.
> Complete rfc5424 header for SyslogUdpHandler

- src/Monolog/Logger.php
In this PR I optimised the hot path for the cases when there are no handlers to handle a message (due to a level).
In my environment the performance gain is about x2-3.
The cost of this change is slightly more complicated message handling code: it is more tangled now (so I'm open for suggestions on how to improve it). And it is likely to be slightly less performant, but in case when a message is handled - the handlers would be the slowest part, so the penalty for the lines I added should be negligible (it is my speculations, it needs a proof).
If necessary and if the dev team agrees this optimisation worth it, I may provide a small set of performance tests (but I'm not a performance engineer and don't do it professionally, so they likely to be not ideal).
So, what would be your thoughts?
> Replaced current/next-style loop with foreach

- src/Monolog/Handler/RollbarHandler.php
- tests/Monolog/Handler/RollbarHandlerTest.php
As mentioned by @AlexStansfield in #852, the level is not properly reflected in Rollbar when reporting exceptions. The issue is closed but it still didn't work for us.
So while digging into the Rollbar library I arrived at the same conclusion that Alex did; that the level has to be included in the payload data to work.
I have verified that this fix works with manual tests. I also took the opportunity to introduce a basic test case for the RollbarHandler as there wasn't one before.
> Add level parameter to payload when reporting Rollbar exceptions (#852)

- src/Monolog/Formatter/GelfMessageFormatter.php
- tests/Monolog/Formatter/GelfMessageFormatterTest.php
The 32766 maximum is default per token but it's configurable in ES and should be configurable in lib as well. Changed total message length maximum to per field basis.
Related to #751
> Gelf max length

- tests/Monolog/Formatter/NormalizerFormatterTest.php
- tests/Monolog/Handler/ElasticSearchHandlerTest.php
- tests/Monolog/Handler/SyslogHandlerTest.php
- tests/Monolog/RegistryTest.php
The `setExpectedException` method is deprecated in PHPUnit 5.2+ and removed in PHPUnit 6. This pull request simply replaces calls to `setExpectedException` with its replacement `expectException` and `expectExceptionMessage` (as needed).
> Replace deprecated setExpectedException in PHPUnit tests.

- tests/Monolog/Handler/RotatingFileHandlerTest.php
When making the calculations for the filename of the current month using
date('d') does not work because you may run into the situation where you run
the tests on a day in a month that does not exist in the previous month,
for example March 30th. As there is no Februari 30th, PHP will skip ahead
to March, and the filename for the "previous" month will incorrectly be
"2017-03" instead of the expected "2017-02". Using the first day of the
month instead of the current day of the month solves this problem.
For consisty we now also use the first month of each year for calculations
regarding years even if this is not necessary, it would break symmetry
if we don't, plus it makes it clear that the value is not relevant in the
calculation.
> Use first day/first month for date calculations in RotatingFileHanderTest

- src/Monolog/Handler/ChromePHPHandler.php
- tests/Monolog/Handler/ChromePHPHandlerTest.php
We've started using Chromium 57 with the `--headless` flag during integration tests. This means we no longer need Xvfb to be installed.
However Chromium changes the Agent string to:
`'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome Safari/537.36'`
this doesn't match ChomeLogger's REGEX so our int tests won't get the Chrome logger data.
Can we have this? We are still on PHP 5.6 so I haven't been able to test against `master`.
Thanks.
> Support HeadlessChrome

- src/Monolog/Handler/SlackWebhookHandler.php
Add getter so that the subclass can easy to inherit SlackWebhookHandler class
> Add getter for webhook url in SlackWebhookHandler class

- src/Monolog/Handler/SlackHandler.php
- src/Monolog/Handler/SlackWebhookHandler.php
We must use another property to store the `private` properties at parent class.
> See an example: https://github.com/104corp/monolog-extensions/blob/master/src/Handlers/ProxyableSlackWebhookHandler.php#L27
It's not a good idea. Please use `protected` visibility so that we can extend slack handlers easily.
> Adjust visibility of some properties to protected for extend slack handlers

- src/Monolog/Handler/AbstractHandler.php
- src/Monolog/Handler/AbstractSyslogHandler.php
- src/Monolog/Handler/BufferHandler.php
- src/Monolog/Handler/ChromePHPHandler.php
- src/Monolog/Handler/DeduplicationHandler.php
- src/Monolog/Handler/ElasticSearchHandler.php
- src/Monolog/Handler/ErrorLogHandler.php
- src/Monolog/Handler/FilterHandler.php
- src/Monolog/Handler/FingersCrossed/ActivationStrategyInterface.php
- src/Monolog/Handler/FingersCrossedHandler.php
- src/Monolog/Handler/FirePHPHandler.php
- src/Monolog/Handler/GroupHandler.php
- src/Monolog/Handler/HandlerInterface.php
- src/Monolog/Handler/IFTTTHandler.php
- src/Monolog/Handler/MandrillHandler.php
- src/Monolog/Handler/PsrHandler.php
- src/Monolog/Handler/PushoverHandler.php
- src/Monolog/Handler/RavenHandler.php
- src/Monolog/Handler/RotatingFileHandler.php
- src/Monolog/Handler/SocketHandler.php
- src/Monolog/Handler/StreamHandler.php
- src/Monolog/Handler/SyslogHandler.php
- src/Monolog/Handler/SyslogUdpHandler.php
- src/Monolog/Logger.php
It might seem a little pedantic, but because the declaration of boolean values in doctypes wasn't in accordance with standards (according to [phpdoc.org](https://docs.phpdoc.org/guides/types.html) and the proposed [PSR-5](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#appendix-a-types)), it sometimes gives issues in my IDE and it always gives problems when running for example [vimeo/psalm](https://github.com/vimeo/psalm) over a project using Monolog, because `Boolean` in the doctype is (rightfully) interpreted as class `Monolog[\Namespace]\Boolean`.
> Rename Boolean in phpDocs to bool on 1.x

- src/Monolog/Processor/IntrospectionProcessor.php
Given we will now only be supporting PHP 7.0 and greater, we can do away with this conditional which offered backwards compatible support to PHP versions less than 5.3.6.
> Remove conditional php version check for debug_backtrace legacy support

- src/Monolog/Formatter/JsonFormatter.php
- tests/Monolog/Formatter/JsonFormatterTest.php
Allow JsonFormatter maximum normalized depth and maximum number of items per level to be configured in the constructor.
Fixes #1094.
> Configurable JsonFormatter maximum normalized depth and number of items

- src/Monolog/Handler/SqsHandler.php
SQS messages have upper limit of their body. 
It's better to log something instead of skip or fail this logg. 
I would prefer to log new error message, when this happen, via logger instance, but it's not accessible there.
i.e.: `$this->logger->error('Too long message for SQS handler [' . $headOfMessage . '...]')` 
Does anybody know, how to achive this and keep constructor minimal?
> Check maximum allowed size of sqs message

- src/Monolog/Handler/ErrorLogHandler.php
otherwise `null` and `false` get accepted as valid types:
```php
$handler = new Handler\ErrorLogHandler(null, $level);
```
note: this is somewhat backward incompatible, as previously `null` and `false` and `""` would be converted to `0`, but now they are rejected.
also, maybe it would make sense to allow `null` to be "use default value `self::OPERATING_SYSTEM`"?
> ErrorLogHandler: use strict comparison

- composer.json
- phpunit.xml.dist
- tests/Monolog/Formatter/LogstashFormatterTest.php
- tests/Monolog/Formatter/NormalizerFormatterTest.php
- tests/Monolog/Handler/ProcessHandlerTest.php
- tests/Monolog/Handler/RotatingFileHandlerTest.php
- tests/bootstrap.php
* PHPUnit 5 is already out of support https://phpunit.de/
* When we require php7, we can use PHPUnit6.
> Compatible to phpunit6

- src/Monolog/Handler/Slack/SlackRecord.php
When message appears in slack channel, there is a problem with cyrillic symbols. They are encoded in unicode and not readable. This fix allow to avoid such problem.
> fix-for-slack-record-encoding

- src/Monolog/ErrorHandler.php
This fixes the castings of param `$fataLevel` to be `string|null|false` as it should be.
> Fix #1066: Use correct docblock castings.

- src/Monolog/Handler/RotatingFileHandler.php
This fixes the handling of comparing $this->nextRotation and $record['datetime'] whether Log-file must be rotated.
At present, Log-file can't be rotated in the case of just 'YYYY-MM-DD 00:00:00.000000'.
> Fix Comparison operator in RotatingFileHandler

- doc/02-handlers-formatters-processors.md
- src/Monolog/Handler/InsightOpsHandler.php
- tests/Monolog/Handler/InsightOpsHandlerTest.php
[Rapid7 bought Logentries](https://www.rapid7.com/about/press-releases/rapid7-acquires-logentries/) and decided to [rebrand it to InsightOps](https://www.rapid7.com/info/logentries-insightops/).
InsightOps works the same way that LogEntries, except that a new endpoint (either on Europe or US) is used.
Since Monolog supports LogEntries, I think its good to support InsightOps as well.
> Include InsightOps handler

- src/Monolog/Handler/AbstractBrowserHandler.php
- src/Monolog/Handler/ChromePHPHandler.php
- src/Monolog/Handler/FirePHPHandler.php
- src/Monolog/Handler/WebRequestRecognizerTrait.php
- tests/Monolog/Handler/ChromePHPHandlerTest.php
- tests/Monolog/Handler/FirePHPHandlerTest.php
I faced the problem that if I use the FirePHP and ChromePHP handlers in a non-web context especially the firephp handler collected a lot of data (it stores every record in an internal array). So if you have a long process (for example a migration task) and the this process logs a lot of data you end up with a huge amount of memory in the end.
This PR checks if monolog/PHP runs in web context and if not doesn't do anything in case of the ChromePHP and FirePHP handlers.
**I will fix the tests once I got feedback for the idea and if it will be accepted.**
> Check if monolog runs in web context

- composer.json
- src/Monolog/Handler/RollbarHandler.php
- tests/Monolog/Handler/RollbarHandlerTest.php
We received a request to update Monolog's `RollbarHandler` to be in sync with the latest version of our SDK ( https://github.com/rollbar/rollbar-php ). The github issue can be found here: https://github.com/rollbar/rollbar-php/issues/249
This PR makes the `RollbarHandler` up to date with `rollbar-php` v1.0+.
Please, review and merge to master if it looks good to go.
> Sync RollbarHandler with the latest changes rollbar/rollbar package

- src/Monolog/Handler/AbstractHandler.php
When running a static analyser against my code, If I'm using Monolog as a PSR-3 Compatible logger, I get a errors similar to the following:-
```
------ --------------------------------------------------------------------------------------------------------- 
Line   console.php                                                                                              
------ --------------------------------------------------------------------------------------------------------- 
47     Parameter #2 $level of class Monolog\Handler\StreamHandler constructor expects int, mixed|string given.  
50     Parameter #2 $level of class Monolog\Handler\StreamHandler constructor expects int, string given.        
57     Parameter #2 $level of class Monolog\Handler\RavenHandler constructor expects …
```
> Update Docblock to specify allowing string Log Levels

- doc/02-handlers-formatters-processors.md
Update AmqpHandler docs to reflect that https://github.com/php-amqplib/php-amqplib can be used in place of ext php-amqp
> Update AmqpHandler Docs

- src/Monolog/Handler/SlackHandler.php
- src/Monolog/Handler/SlackWebhookHandler.php
During constructiong the SlackHandler a Formatter has not been set.
So it does not make sense passing the Formatter as an argument to SlackRecord. It is just confusing and makes people wonder where this has been set?
> Remove from slack handler on constructing the SlackRecord to pass the Formatte

- src/Monolog/Handler/NewRelicHandler.php
Support for correct passing of Throwable to newrelic_notice_error() in PHP7 as outlined in #1145
> NewRelicHandler - handle Throwable in PHP7

- src/Monolog/ErrorHandler.php
Fixes #693
See discussion on this ticket.
> ENHANCEMENT Ensure 'trace' is captured for fatal non-exceptions

- src/Monolog/Formatter/LogstashFormatter.php
- tests/Monolog/Formatter/LogstashFormatterTest.php
It doesn't really make sense to let half of the key be configurable and the other half hardcoded.
Previously, the prefixes made sense because it wasn't a nested array so each key was dynamic.
> Change LogstashFormatter prefix properties to keys

- src/Monolog/Handler/SocketHandler.php
- tests/Monolog/Handler/SocketHandlerTest.php
This pull requests adds an option to the SocketHandler to set the desired stream chunk size via `stream_set_chunk_size`.
The main problem this pull request solves is logging larger messages via UDP using SocketHandler. The default chunk size set by PHP appears to be 8192 and any larger UDP messages get split into multiple packets and result in multiple log entries. When used with logstash (and similar processors) those messages are therefore not parsed correctly.
Since the UDP protocol allows for much larger packets (https://en.wikipedia.org/wiki/User_Datagram_Protocol#Packet_structure), this problem can be solved by simply using a larger chunk size.
> Allow setting stream chunk size in SocketHandler

- src/Monolog/Formatter/LineFormatter.php
- tests/Monolog/Formatter/LineFormatterTest.php
> Include stacktraces for "previous" excpetions in LineFormatter

- src/Monolog/Processor/GitProcessor.php
- src/Monolog/Processor/IntrospectionProcessor.php
- src/Monolog/Processor/MemoryProcessor.php
- src/Monolog/Processor/MercurialProcessor.php
- src/Monolog/Processor/ProcessIdProcessor.php
- src/Monolog/Processor/ProcessorInterface.php
- src/Monolog/Processor/PsrLogMessageProcessor.php
- src/Monolog/Processor/TagProcessor.php
- src/Monolog/Processor/UidProcessor.php
- src/Monolog/Processor/WebProcessor.php
Would replace https://github.com/symfony/symfony/pull/27801, as an interface better belongs to its original package than to a bridge.
> Add ProcessorInterface, an optional one to allow labelling Monolog processors

- src/Monolog/Formatter/GelfMessageFormatter.php
The @see URL for GELF was broken so I found the new URL and updated it in the PHPDoc.
> Updated @see URL for GELF formatter.

- README.md
As the official site says, Silex is in maintainence mode and is no longer actively developed. Maybe it should be removed here as a reference to discourage people from building upon it. But maybe you should keep it here for people still using it, though.
> removed Silex, as it is no longer actively developed

- CHANGELOG.md
- src/Monolog/Handler/AbstractHandler.php
- src/Monolog/Handler/AbstractProcessingHandler.php
- src/Monolog/Handler/BrowserConsoleHandler.php
- src/Monolog/Handler/BufferHandler.php
- src/Monolog/Handler/FingersCrossedHandler.php
- src/Monolog/Handler/GroupHandler.php
- src/Monolog/Handler/HandlerWrapper.php
- src/Monolog/Logger.php
- src/Monolog/Processor/UidProcessor.php
- src/Monolog/ResettableInterface.php
- tests/Monolog/Handler/BrowserConsoleHandlerTest.php
- tests/Monolog/Handler/ChromePHPHandlerTest.php
- tests/Monolog/Handler/FingersCrossedHandlerTest.php
- tests/Monolog/Handler/FirePHPHandlerTest.php
- tests/Monolog/LoggerTest.php
Added a new ResetableInterface and implemented it where possible.
When one use Monolog in a long process like an AMQP worker with a
`FingersCrossedHandler` or `BufferHandler` there is a drawback: as soon as there
is an AMQP message that generate a log >= error (for example), all next AMQP
messages will output logs, even if theses messages don't generate log where
level >= error.
In the same context there is a drawback for processor that add an UUID to the
logs. The UUID should change for each AMQP messages.
---
This patch address this issue with a new interface: `ResettableInterface` interface.
Side note: `reset()`, `flush()`, `clear()`,  are already used in Monolog. So
basically, one can use the `reset()` on the `Logger` and on some
`Handler`s / `Processor`s.
It's especially useful for
* …
> Added a new ResettableInterface and implemented it where possible.

- .gitattributes
Hi,
Let's not publish all those file.
`.gitattributes` can be used to exclude files from final archive that is downloaded by composer.
This file content is same as `master` branch now.
Thanks.
> Exclude files and folder from release archive

- src/Monolog/Formatter/GelfMessageFormatter.php
- src/Monolog/Formatter/JsonFormatter.php
- src/Monolog/Formatter/LineFormatter.php
- src/Monolog/Formatter/LogmaticFormatter.php
- src/Monolog/Formatter/NormalizerFormatter.php
- src/Monolog/Formatter/WildfireFormatter.php
- src/Monolog/Handler/ChromePHPHandler.php
- src/Monolog/Handler/DynamoDbHandler.php
- src/Monolog/Handler/ErrorLogHandler.php
- src/Monolog/Handler/FirePHPHandler.php
- src/Monolog/Handler/FleepHookHandler.php
- src/Monolog/Handler/HipChatHandler.php
- src/Monolog/Handler/LogglyHandler.php
- src/Monolog/Handler/ProcessHandler.php
- src/Monolog/Handler/RotatingFileHandler.php
- src/Monolog/Handler/Slack/SlackRecord.php
- src/Monolog/Handler/SqsHandler.php
- src/Monolog/Handler/SyslogUdp/UdpSocket.php
- src/Monolog/Logger.php
- src/Monolog/Processor/PsrLogMessageProcessor.php
[PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md) Just for reference if it gets accepted: 
> Visibility MUST be declared on all constants if your project PHP minimum version supports constant visibilities (PHP 7.1 or later).
Personally I like it also this way better. Maybe you should revise some of them if they should be public but this would be a BC. Since you are moving to v2.0 it's a good chance.
> Add visibility to constants

- src/Monolog/Handler/Curl/Util.php
- src/Monolog/Utils.php
Hello,
Should these be final and internal to avoid BC changes in the future.
I am not sure if you would be willing to accept a change like this... 
Also I have one more suggestion to make.. how would you feel about removing the Curl Util and moving to a solution like HTTPlug now that PSR-18 is accepted?
> Make CURL util final and internal

- src/Monolog/Handler/HandlerWrapper.php
The parameter `$formatter` was never set and most probably it would have caused a fatal error.
> Parameter formatter was never set.. would cause fatal

- src/Monolog/ErrorHandler.php
According to official PHP documentation 
> Returns the value of the configuration option as a string on success, or an empty string for null values. Returns FALSE if the configuration option doesn't exist. 
This change seems kinda big... and I don't know how to test it
> Error handler strict comparison fix

- README.md
The old URL is no longer in use, serving "Logbook's documentation is maintained elsewhere." and a redirect.
> Update README link of Python Logbook

- src/Monolog/Formatter/NormalizerFormatter.php
I needed this change because I have exceptions that I want to handle how they get json serialized.
> Check for JsonSerializable in normalizeException

- src/Monolog/Handler/GroupHandler.php
- src/Monolog/Handler/WhatFailureGroupHandler.php
- tests/Monolog/Handler/GroupHandlerTest.php
- tests/Monolog/Handler/WhatFailureGroupHandlerTest.php
Fix create duplicate records in *GroupHandler when there is more than one Processor.
> Fix create duplicate records in *GroupHandler 1.x

- src/Monolog/Formatter/NormalizerFormatter.php
Sometimes you want to add some options. In my case I wanted to encode the data using JSON_FORCE_OBJECT, but there was no way to do it
> Enable adding/removing options to json_encode()

- src/Monolog/Handler/Slack/SlackRecord.php
See docs here: https://api.slack.com/docs/interactive-message-field-guide
Slack will automatically limit this for us, but it will remove the last 3 back ticks so long messages is not properly formatted.
> Dont use more than 2000 chars for slack attachments field

- src/Monolog/Processor/MemoryPeakUsageProcessor.php
- src/Monolog/Processor/MemoryUsageProcessor.php
Determining accurate memory usage should be an optimized process, not introducing any extra overhead. This pull request uses just a single variable and avoids a function call, if it's not needed.
1. Combine `$bytes` and `$formatted` into single `$usage` variable.
2. Check to see if formatting is needed before calling `formatBytes()`.
> optimize MemoryUsage processors

- src/Monolog/Formatter/GelfMessageFormatter.php
If the first element in the array has exceeded the maximum message length, then the following elements are ignored.
> Fixed gelf formatter

- src/Monolog/Processor/ProcessorInterface.php
Every single processor that implements `ProcessorInterface` has only single record as argument. This is true even when I test the code in my project.
Having the ProcessorInterface argument for multiple records is seriously confusing and untrue.
> fix ProcessorInterface

- .travis.yml
According to https://externals.io/message/103862  nightly is php 8.0
> Test on php 7.4 only

- src/Monolog/Handler/Curl/Util.php
Simply rework `Curl\Util::execute()` method. So now this method returns HTTP response from the request.
Moreover, because this method returns nothing - these changes do not break anything.
> Change Curl\Util for return response from cURL request.

- src/Monolog/Handler/RotatingFileHandler.php
With this change you can use two digit years, i.e. $fileHandler->setFilenameFormat('{date}_{filename}', 'y-m-d'); for 19-03-21
> support two digit years

- doc/02-handlers-formatters-processors.md
The current link no longer exists so this is the most extensive and popular page for the logrotate command.
> Replace logrotate link with alternative page

- src/Monolog/Handler/TelegramBotHandler.php
- tests/Monolog/Handler/TelegramBotHandlerTest.php
Add handler which can send logs to Telegram using [Telegram Bot API](https://core.telegram.org/bots/api).
Handler depends only on the cURL extension.
P.S. seems that travis-ci failed because of PHP-version ^7.1 in composer.json but [CI use 8.0.0-dev](https://travis-ci.org/Seldaek/monolog/jobs/550408854)
> Add telegram bot handler.

- src/Monolog/Handler/Slack/SlackRecord.php
- src/Monolog/Handler/SlackHandler.php
The current slack handler has way too many constructor parameters and no clear order as to their position. This makes it confusing to work out what is actually trying to be set when constructing a new class, e.g,
``` php
$slack = new SlackHandler(
'xoxp-0000000000-1111111111-22222222222-3333333333',
'#general',
'Monolog',
false,
null,
Logger::ERROR,
true,
false,
true
);
```
This PR makes things a bit easier by adding some fluent setters into the class.
``` php
$slack = new SlackHandler(
'xoxp-0000000000-1111111111-22222222222-3333333333',
'#general',
'Monolog'
)
->setErrorLevel(Logger::ERROR)
->useAttachment(false)
->includeContextAndExtra(true);
```
It would be nice to cut back the number of constructor parameters and reorder them to make a bit more sense
``` php
// Current
public …
```
> Add fluent setters for parameters in the slack handler

- UPGRADE.md
> Fix typo in Upgrade Guide

- README.md
Old link links to a domain for sale page. Domain must have expired.
> Fixed broken link to PPI framework

- src/Monolog/Logger.php
As part of its migration to PHP 7.2, Symfony is starting to require more explicit annotations for return-type. ~Of course, Monolog cannot add real ones here, due to BC.~ These declarations would help us (and would make our CI green again as we now have a check to ensure the code and its deps are in good shape in this regard, see e.g. https://travis-ci.org/symfony/symfony/jobs/571836979)
Cannot be applied on branch 1.x since it has conflicting `@return bool`.
> Add explicity void return type to Monolog\Logger

- doc/02-handlers-formatters-processors.md
- src/Monolog/Handler/FallbackGroupHandler.php
- tests/Monolog/Handler/ExceptionTestHandler.php
- tests/Monolog/Handler/FallbackGroupHandlerTest.php
- tests/Monolog/Handler/WhatFailureGroupHandlerTest.php
- Adds `FallbackGroupHandler` to attempt to send to a series of handlers, breaking once one is successfully handled. 
- Code adapted from https://github.com/Seldaek/monolog/issues/590#issuecomment-359484395
- Moved `ExceptionTestHandler` to own class - exception thrown before handled to simulate real world situation. Otherwise TestHandler would have the record.
> Add FallbackGroupHandler

- src/Monolog/ErrorHandler.php
- src/Monolog/Handler/StreamHandler.php
- tests/Monolog/Formatter/NormalizerFormatterTest.php
- tests/Monolog/Handler/RotatingFileHandlerTest.php
Hi,
Small patch to fix error handler function return type.
From php.net documentation, the error_handler should return a bool and not a void (https://www.php.net/manual/en/function.set-error-handler.php).
> Fix error_handler return type declaration

- src/Monolog/Handler/SyslogUdpHandler.php
Hello!
As described in [this issue](https://github.com/Seldaek/monolog/issues/1350), SyslogUdpHandler doesn't respect `Logger` timezone setting for IETF (RFC-5424) syslog format.
This PR is a fix for this issue.
> Fix for SyslogUdpHandler timezone issue

- CHANGELOG.md
- src/Monolog/Formatter/JsonFormatter.php
- src/Monolog/Formatter/NormalizerFormatter.php
- tests/Monolog/Formatter/NormalizerFormatterTest.php
- tests/Monolog/Formatter/ScalarFormatterTest.php
> Normalize the way backtraces are normalized and remove args for special cases

- README.md
Since there is no reason to use shields for the build status badge we can use it directly from travis-ci.
> Use svg for build status directly from travis-ci

- .php_cs
- composer.json
- src/Monolog/Handler/FormattableHandlerInterface.php
- src/Monolog/Handler/FormattableHandlerTrait.php
- src/Monolog/Handler/ProcessableHandlerInterface.php
- src/Monolog/Handler/ProcessableHandlerTrait.php
New features should have been done on 1.X and 2.X should be for cleanup.
Now it's too late, but we can ease migrations by backporting some
code to 1.X.
This PR will help supporting monolog 1.X and 2.X at the same time.
See https://github.com/symfony/symfony/pull/33241
> Backport Interface and Trait from master to 1.X

- README.md
We recently released v6.0 so maybe we shouldn't mention the versions anymore. Monolog will probably always remain with the framework.
Thanks for all your work on Monolog and Composer @Seldaek!
> Remove versions from Laravel integration

- src/Monolog/Handler/ChromePHPHandler.php
Due to change in chromium header size support, the size limit enforced by the handler must be decreased.
See issue #1371
> Change chrome header size limit

- src/Monolog/Handler/FormattableHandlerInterface.php
- src/Monolog/Handler/FormattableHandlerTrait.php
- src/Monolog/Handler/ProcessableHandlerInterface.php
- src/Monolog/Handler/ProcessableHandlerTrait.php
I'm sorry the extra work. But while working on https://github.com/symfony/symfony/pull/33492 I notice traits were not forward compatible.
So I:
* removed the `@internal ` flag, as the goal of theses traits is to be used.
* fixed the signature, to be compatible with the current signature of `Mono
log\Handler\AbstractHandler::pushProcessor($callback)`
The error was:
```
1x: The "Monolog\Handler\ProcessableHandlerTrait" trait is considered internal This interface is present in monolog 1.x to ease forward compatibility. It may change wit
hout further notice. You should not use it from "Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler".                                                            
1x in DeprecationErrorHandler::shutdown from Symfony\Bridge\PhpUnit …
```
> Fixed forward compatibilty layer

- src/Monolog/Formatter/HtmlFormatter.php
My case is if you log php trace into `context` it will throw an error
`Argument 1 passed to Monolog\\Formatter\\HtmlFormatter::addRow() must be of the type string, int given`.
The PR fixes the issue
> HtmlFormatter cast key to string in addRow

- .github/SECURITY.md
Tying in with #1389, this will add a new section
to the 'create new issue' and also be visible in the
'security' tab on GitHub
It's been left intentionally generic.
examples: 
https://github.com/Zarthus/monolog/security/policy
https://github.com/Zarthus/monolog/issues/new/choose
in an established project: https://github.com/symfony/symfony/issues/new/choose
> github: Add security header

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/Bug_Report.md
- .github/ISSUE_TEMPLATE/Feature.md
- .github/ISSUE_TEMPLATE/Question.md
Moves away from the older version of GitHub issue templates, includes
automatic labelling.
more reading:
https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
see it in action: https://github.com/Zarthus/monolog/issues
> github: implement newer version of issue templates

- src/Monolog/Formatter/JsonFormatter.php
Iterators and Generators may not be rewindable, so foreach is not safe
to use on them.
Iterators and especially Generators may trigger irreversible actions on
calling next(), so iterating over all values can potentially cause harm,
e.g. imagine an iterator over a set of HTTP POST requests that are sent
when the next value is requested . The only sufficiently safe thing to
iterate and include here are primitive arrays.
similar fix is applied to `NormalizerFormatter`: https://github.com/Seldaek/monolog/pull/891/files
It throws `Exception : Cannot traverse an already closed generator vendor/monolog/monolog/src/Monolog/Formatter/JsonFormatter.php:152`:
```php
public function getGenerator(): \Generator
{
yield 111;
yield 222;
}
public function testNormalizeClosedGenerator()
{
$formatter = new …
```
> JsonFormatter: Don't even try to attempt normalizing iterators or generators in context

- src/Monolog/Handler/ElasticsearchHandler.php
#1405 
Previously exceptions were thrown like this:
Error sending messages to Elasticsearch
Elasticsearch returned error for one of the records
After this fix:
Error sending messages to Elasticsearch	
mapper_parsing_exception: failed to parse field [ip] of type [text] in document with id '5Fvd324BEf_D0jiFiYl-'` 
illegal_state_exception: Can't get text on a START_OBJECT at 1:2616
If no useful info is found in the `responses` array, falls back to:
'Elasticsearch failed to index one or more records.'
Didn't mean to reorder imports, IDE did it automatically.
> More detailed ElasticsearchHandler exceptions

- src/Monolog/Logger.php
PHP's `strtoupper()` is locale-aware, and `strtoupper('i')` (= `strtoupper(chr(105))`) will not be `I`(= `chr(73)`) but `chr(221)`, the "latin capital letter i with dot above" İ character.
> Fix a bug when using string-based loglevels in the `tr_TR` locale

- src/Monolog/Handler/StreamHandler.php
- tests/Monolog/Handler/StreamHandlerTest.php
The `\Exception` for non-existing and not creatable paths is thrown earliest on first write.
Not during StreamHandler instantiation, as claimed by the constructor's `@throws` tag.
> Fix misleading @throws tag in StreamHandler doc

- README.md
"which" is associated with things, "who" is more suitable for humans.
> Correct pronoun in readme for contributors

- src/Monolog/Handler/RedisHandler.php
Set the default function parameter to avoid potential issues when a Redis proxy is used instead of the internal class.
This issue has been discussed in https://github.com/phpredis/phpredis/issues/1476#issuecomment-445968070 and https://github.com/snc/SncRedisBundle/issues/442.
This may be Symfony specific, but I'd be happy to hear your thoughts on this issue.
> Set phpredis multi() mode parameter

- README.md
Hi, kdyby/monolog package is no longer maintained.
> Replace old Nette Framework extension with new one

- src/Monolog/Handler/AbstractHandler.php
The level parameter of the `AbstractHandler` supports also the PSR levels as strings e.g. `\Psr\Log\LogLevel::ERROR` or from a ENV variable `CUSTOM_ERROR_HANDLER_LEVEL=error`.
This will fix issues with phpstan or other static code analyzer when given the level as string.
> Fix typehint for AbstractHandler level parameter

- src/Monolog/Formatter/HtmlFormatter.php
Hi,
Just a PR that remap new html colors on bootstrap ones, that IMO a lot of developers are visually used to :)
cf https://github.com/twbs/bootstrap/blob/master/site/data/colors.yml
(exepts for the `alert` where  i took the `critical` but darker)
before:
after:
> Update html color

- src/Monolog/ErrorHandler.php
The use statement `use Monolog\Registry;` was unnecessary in the `ErrorHandler` class.
> Registry class not used in ErrorHandler

- src/Monolog/Formatter/JsonFormatter.php
- tests/Monolog/Formatter/JsonFormatterTest.php
> JsonFormatter: add option to ignore empty `context` and `extra` fields

- src/Monolog/Handler/TelegramBotHandler.php
- tests/Monolog/Handler/TelegramBotHandlerTest.php
The telegram API for sendMessage supports some additional parameters that where not yet covered with the current implementation. See the API documentation here:
https://core.telegram.org/bots/api#sendmessage
In my use case I'm mostly just interested in the `parse_mode` parameter but I thought that while I'm on it I could also add support for `disable_web_page_preview` and `disable_notification`.
I didn't add support for the other remaining options because in my opinion they will never make sense when using the API for logging. `reply_to_message_id` can only be set for replies, but when logging we're not replying to a message but rather sending independent messages. `reply_markup` lets the bot display an interactive interface for the user receiving the message, but the log handler can't …
> Telegram Handler: support additional API parameters

- src/Monolog/Handler/RavenHandler.php
PHP 7.4 introduces backward incompatible changes and not allow anymore to [access a null variable like an array](https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.non-array-access).
The `RavenHandler` use an `array_reduce` with the default initial value that is `null` but acces it like an array which generate a PHP notice.
> Fix array offset access on null in RavenHandler

- src/Monolog/Handler/FilterHandler.php
- src/Monolog/Handler/FingersCrossedHandler.php
- src/Monolog/Handler/MandrillHandler.php
- src/Monolog/Handler/ProcessableHandlerInterface.php
- src/Monolog/Handler/SamplingHandler.php
- src/Monolog/Handler/SwiftMailerHandler.php
- src/Monolog/Handler/TestHandler.php
- src/Monolog/Logger.php
Hi.. although you are not using static analysis these docblocks can improve static analysis on userland.
- I used `psalm-*` in order for the normal annotations to not mess the IDEs
- The `psalm-*` annotation works both for psalm and phpstan. I think that also psalm reads `phpstan-*` annotations.
- Since you don't use static analysis I only changed the public api.
More things could be done. Like adding to levels something like this:
```php
psalm-param 100|200|300|400|550|600|LogLevel::* $level
```
But it wont be 100% accurate since level can accept `info` and `INFO` and `iNFO` so I believe it's not worth the overhead.
> Static analysis improvements

- src/Monolog/Handler/SyslogUdpHandler.php
As described in [RFC5424 Timestamp format](https://tools.ietf.org/html/rfc5424#section-6.2.3), it is allowed to send second fraction as doted mili (3 digits) or micro (6 digits) in syslog messages. I suggest this modest PR to support it.
> Support for extended RFC5424 timestamp format

- src/Monolog/Logger.php
This allows for log level to be string numeric in case of setting from environment variables or other sources with ambivalent type
> Allow string numeric log levels

- src/Monolog/Handler/HandlerWrapper.php
Method `setFormatter` in `HandlerWrapper` always throws an exception, fixed it.
> Adds return value in handler wrapper

- src/Monolog/Utils.php
getClass is not internal method
> remove @internal annotation

- src/Monolog/Logger.php
I was wondering if next/current is faster than foreach. The test
```<?php
$startTime = microtime(true);
for ($i = 1; $i < 1000000; $i++) {
$handlerList = [];
$handlerList[] = 'a';
$handlerList[] = 'b';
$handlerList[] = 'c';
$handlerList[] = 'd';
foreach ($handlerList as $key => $handler) {
}
}
echo 'foreach      - ' . (microtime(true) - $startTime) . "\n";
$startTime = microtime(true);
for ($i = 1; $i < 1000000; $i++) {
$handlerList = [];
$handlerList[] = 'a';
$handlerList[] = 'b';
$handlerList[] = 'c';
$handlerList[] = 'd';
while ($handler = current($handlerList)) {
next($handlerList);
}
}
echo 'next/current - ' . (microtime(true) - $startTime) . "\n";
```
```
foreach      - 0.17546820640564
next/current - 0.38347506523132
```
http://sandbox.onlinephpfunctions.com/code/0c1d5b1a723309ce669 …
> Speed up Logger::addRecord

- src/Monolog/Handler/RedisPubSubHandler.php
- tests/Monolog/Handler/RedisPubSubHandlerTest.php
This adds a basic Handler which pushes messages to a Pub/Sub Redis channel.
Let me know if you think it should be rewritten as part of the existing Redis handler - or if this is fine!
> Adding Redis Pub/Sub handler (closes #574)

- composer.json
- src/Monolog/Formatter/ElasticaFormatter.php
- src/Monolog/Handler/ElasticaHandler.php
- tests/Monolog/Formatter/ElasticaFormatterTest.php
- tests/Monolog/Handler/ElasticaHandlerTest.php
If you use the Elastica 7 client, which is only compatible with v7 of ElasticSearch, support of types has been dropped. This PR tests for the Elastica client version and conditionally drops types if they are no longer supported.
It replaces #1476 that mistakes `OpType` (operation type) parameter for ES types.
Resolves #1399
> Support for Elastica client up to v7.0.0, with optional drop support for ES types

- src/Monolog/Handler/FilterHandler.php
- tests/Monolog/Handler/FilterHandlerTest.php
When we reset the FilterHandler we should call the handler we are wrapping.
> Reset wrapped handler of the FilterHandler

- tests/Monolog/Handler/AmqpHandlerTest.php
- tests/Monolog/Handler/DoctrineCouchDBHandlerTest.php
- tests/Monolog/Handler/DynamoDbHandlerTest.php
- tests/Monolog/Handler/ElasticaHandlerTest.php
- tests/Monolog/Handler/ElasticsearchHandlerTest.php
- tests/Monolog/Handler/FlowdockHandlerTest.php
- tests/Monolog/Handler/GelfHandlerTest.php
- tests/Monolog/Handler/InsightOpsHandlerTest.php
- tests/Monolog/Handler/LogEntriesHandlerTest.php
- tests/Monolog/Handler/LogmaticHandlerTest.php
- tests/Monolog/Handler/PHPConsoleHandlerTest.php
- tests/Monolog/Handler/ProcessHandlerTest.php
- tests/Monolog/Handler/PushoverHandlerTest.php
- tests/Monolog/Handler/RedisHandlerTest.php
- tests/Monolog/Handler/RollbarHandlerTest.php
- tests/Monolog/Handler/SlackHandlerTest.php
- tests/Monolog/Handler/SocketHandlerTest.php
- tests/Monolog/Handler/SyslogUdpHandlerTest.php
- tests/Monolog/Handler/TelegramBotHandlerTest.php
- tests/Monolog/Handler/UdpSocketTest.php
- tests/Monolog/Handler/ZendMonitorHandlerTest.php
- tests/Monolog/LoggerTest.php
`MockBuilder::setMethods()` is marked as deprecated since PHPUnit 8, but it's used in monolog tests.
In this pull request I've replaced these calls to `onlyMethods()` / `addMethods()`.
Summary of changes:
1. the replace `setMethods()` -> `onlyMethods()` was enough in most cases
2. `DynamoDbHandlerTest` has a tricky case (Aws\DynamoDb\DynamoDbClient:: formatAttributes exists in aws/aws-sdk-php v2, but was removed in v3.0, but its call was tested based on the version)
3. AmqpHandlerTest requires the checking of `\PhpAmqpLib\Channel\AMQPChannel::__destruct` existence before the onlyMethods() usage (because __destruct was removed in php-amqplib/php-amqplib:2.5.0)
4. RedisHandlerTest requires the usage of `addMethods()` because Predis\Client uses magic method `__call()` for commands processing
> Stop using deprecated MockBuilder::setMethods in unit tests

- src/Monolog/Logger.php
PHP 8.1 issues a deprecation warning for Monolog:
> DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated
This PR attempts to fix the problem.
> Fix deprecation warning on PHP 8.1

- src/Monolog/Formatter/JsonFormatter.php
Hello! :)
This seems to be a leftover from #1459: JsonFormatter is not respecting the content of FormatterInterface->dateFormat.
The problem is because JsonFormatter extends the `normalize` method, but doesn't handle `DateTimeInterface` objects the same way `parent::normalize()` does. This PR fixes the issue. :)
> JsonFormatter::normalize() : respect date format from Formatter

- src/Monolog/Utils.php
- tests/Monolog/UtilsTest.php
The results of this function differ over PHP versions since from PHP8 anonymous classes names don't necessarily start by _class_.
This PR takes also into account that _get_class_parent()_ may return _false_.
> Fix Utils::getClass() with PHP8

- src/Monolog/Handler/StreamHandler.php
- src/Monolog/Utils.php
- tests/Monolog/Handler/StreamHandlerTest.php
- tests/Monolog/UtilsTest.php
Fixes Issue #1577 
This change is meant to prevent setting a stream chunk size bigger than the available amount of memory.
The default value is still set, but can get change after calculations based on the php settings and the memory currently used by the php process.
There is a hard limit for an stream size of 2G ... is does not matter if the PHP process gets 1000 G of memory, the stream size cannot be bigger than 2G! and I suspect is because of some C lib used behind the scenes to implement streams in PHP.
Also ... the official PHP documentation states that `stream_set_chunk_size()` can hold a value of PHP_INT_MAX , but this is not completely true, because no matter what, it cannot be bigger than 2G! (because of the reason I already mentioned.
I suspect that if maybe the libs used in …
> Fix - OutOfMemory error in StreamHandler

- doc/01-usage.md
monolog-cascade doesn't support monolog ^2.0 or php8
see related issues on theorchard/monolog-cascade:
https://github.com/theorchard/monolog-cascade/issues/90
https://github.com/theorchard/monolog-cascade/issues/102
> Removing mention of monolog-cascade

- .github/workflows/continuous-integration.yml
- composer.json
- phpstan.neon.dist
- tests/Monolog/Handler/RollbarHandlerTest.php
- tests/Monolog/PsrLogCompatTest.php
This PR takes over #1564 and works around https://github.com/rollbar/rollbar-php/pull/536 and https://github.com/php-fig/log-util/pull/2 to make tests pass while allowing psr/log v2 to be installed.
> Allow psr/log 2.0

- src/Monolog/Handler/IFTTTHandler.php
- src/Monolog/Handler/SendGridHandler.php
- src/Monolog/Handler/SlackWebhookHandler.php
- src/Monolog/Handler/TelegramBotHandler.php
There are some handlers which require the curl extension without any check, if the extesnsion is loaded.
> add checks for required curl extension

- src/Monolog/Handler/SyslogUdpHandler.php
The UdpSocket used in the SyslogUdpHandler requires the sockets extension. This PR will add a check for this.
Fixes #1569
> add check for required extension

- src/Monolog/Handler/FleepHookHandler.php
- src/Monolog/Handler/FlowdockHandler.php
- src/Monolog/Handler/InsightOpsHandler.php
- src/Monolog/Handler/LogEntriesHandler.php
- src/Monolog/Handler/LogmaticHandler.php
- src/Monolog/Handler/PushoverHandler.php
- src/Monolog/Handler/SlackHandler.php
- src/Monolog/Handler/SocketHandler.php
Hey there,
I'd like to propose a PoC to allow constructor injection for the `SocketHandler` and its children.
Is that something you want to support within monolog?
If not, I'd be fine with closing this. I can wrap around this and implement this as a feature in a dedicated abstraction layer tho.
Thanks in advance,
Max
> Add constructor injection for `SocketHandler` and its children

- src/Monolog/Attribute/AsMonologProcessor.php
- tests/Monolog/Attribute/AsMonologProcessorTest.php
Ref https://github.com/symfony/monolog-bundle/pull/428
This PR adds an attribute that third-party consumers can leverage to "configure" Monolog processors.
I didn't find any real benefits in supporting it directly in Monolog's `pushProcessor()` methods:
1. We would need to widen the type from `callable` to `callable|object` to accept any objects potentially using the attribute, and that would be a BC break.
2. Monolog would only use the `method` "option" and it doesn't bring any real value, it's already easy to do:
```php
->pushProcessor([$myProcessor, 'myCustomMethod'])
```
cc @derrabus and @nicolas-grekas
> Add AsMonologProcessor attribute

- src/Monolog/Formatter/JsonFormatter.php
- src/Monolog/Formatter/LineFormatter.php
- src/Monolog/Formatter/NormalizerFormatter.php
- src/Monolog/Logger.php
Just an example i just ran into:
```php
$formatter = (new LineFormatter)
->setJsonPrettyPrint(true) // -> LineFormatter instance
->addJsonEncodeOption(JSON_UNESCAPED_SLASHES) // -> void
->addJsonEncodeOption(JSON_UNESCAPED_UNICODE); // boo!
```
I didn't go through the handler classes to check for similar cases.
> return self on builder methods for more consistent behaviour

- src/Monolog/Handler/TelegramBotHandler.php
The maximum allowed length of a Telegram message - 4096 symbols (['text' field](https://core.telegram.org/bots/api#message)). 
Longer messages are not delivered.
Therefore, I implemented truncating too long message to the maximum length allowed as the default behavior. 
An additional option that you can enable by `splitLongMessages` is  splitting too long message into several. Also, using `delayBetweenMessages` you can enable a 1 second delay between sending a split message to avoid the _429 Too Many Requests_ error (according to the recommendations - [My bot is hitting limits, how do I avoid this?](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this))
> Handling the maximum length of a Telegram message

- src/Monolog/Formatter/GelfMessageFormatter.php
To make it obvious, the package is required to use the formatter.
> Check whether graylog2/gelf-php is installed  in GelfMessageFormatter constructor

- src/Monolog/Handler/Slack/SlackRecord.php
- tests/Monolog/Handler/SlackWebhookHandlerTest.php
related to https://github.com/Seldaek/monolog/issues/1247 & https://github.com/Seldaek/monolog/issues/1332
Since userIcon & username cannot be overridden, the text & smaller icon in footer can be used instead.
> SlackWebhookHandler: use footer for username & footer_icon for userIcon

- src/Monolog/Formatter/MongoDBFormatter.php
- tests/Monolog/Formatter/MongoDBFormatterTest.php
I like to throw MongoDB document IDs in my log context so I can cross-reference them later:
```php
$log->info("{$user->email} logged in", [ 'actor' => $user->id ]);
```
Right now, `\Monolog\Formatter\MongoDBFormatter` flattens ObjectIds into arrays (e.g. `[ 'oid' => 'object id string', 'class' => ObjectId::class ]`). This PR allows all `\MongoDB\BSON\Type` implementations to pass through the formatter without additional processing.
> Store native BSON types as-is in the MongoDB formatter

- src/Monolog/Handler/BrowserConsoleHandler.php
This will allow to get rid of reimplementation of wheel here https://github.com/symfony/symfony/pull/43065/files#diff-b1c0588c5bb7078514aaa70581e920b852b49d9614f687950b6be6495afa7693R29-R42
> Allow easier extend of BrowserConsoleHandler.php

- tests/Monolog/Handler/StreamHandlerTest.php
In PHP versions prior to 8.0 failed was lowercase, after the version 8.0 failed is uppercase
> Calculate expected exception message according to PHP version

- src/Monolog/Processor/IntrospectionProcessor.php
$record['extra']['callType'] will contain current call type: "->" or "::" depending if it was normal or static method call.
Gives possibility to nicely format messages "{$record['extra']['class']}{$record['extra']['callType']}{$record['extra']['function']} ..."
> IntrospectionProcessor returns also information about call type

- src/Monolog/ErrorHandler.php
- src/Monolog/Utils.php
The `never` return typehint was added in PHP 8.1 and can be used
to indicate that a function will never return.
RFC: https://wiki.php.net/rfc/noreturn_type
> Use never return typehint

- src/Monolog/ErrorHandler.php
- src/Monolog/Formatter/JsonFormatter.php
- src/Monolog/Handler/Slack/SlackRecord.php
- src/Monolog/Utils.php
The `match` expression is available as of PHP 8.0 and provides a more
intuitive interface than `switch` when a single value is returned.
Note that it performs an identity check (===) between the value and
case instead of a weak equality check (==).
https://www.php.net/manual/en/control-structures.match.php
> Replace switch with match

- .gitattributes
Look like the line is incomplete, example: https://github.com/Seldaek/monolog/commit/7ce63f964426a57b6a1c213d45e05eef1f013c54 `Add missing export-ignore`
> Forgotten config

- composer.json
- src/Monolog/Handler/SwiftMailerHandler.php
- src/Monolog/Handler/SymfonyMailerHandler.php
- tests/Monolog/Handler/SymfonyMailerHandlerTest.php
Fixes #1638
Fixes #1621
It accepts MailerInterface or TransportInterface to be interoperable with Laravel too as per https://github.com/Seldaek/monolog/issues/1638#issuecomment-1065085268
> Add SymfonyMailerHandler, deprecate SwiftMailerHandler

- .github/workflows/continuous-integration.yml
- composer.json
- phpstan.neon.dist
- src/Monolog/Handler/ElasticsearchHandler.php
- src/Monolog/Test/TestCase.php
- tests/Monolog/Formatter/ScalarFormatterTest.php
- tests/Monolog/Handler/AmqpHandlerTest.php
- tests/Monolog/Handler/DynamoDbHandlerTest.php
- tests/Monolog/Handler/ElasticaHandlerTest.php
- tests/Monolog/Handler/ElasticsearchHandlerTest.php
- tests/Monolog/Handler/FlowdockHandlerTest.php
- tests/Monolog/Handler/HandlerWrapperTest.php
- tests/Monolog/Handler/InsightOpsHandlerTest.php
- tests/Monolog/Handler/LogEntriesHandlerTest.php
- tests/Monolog/Handler/LogmaticHandlerTest.php
- tests/Monolog/Handler/PHPConsoleHandlerTest.php
- tests/Monolog/Handler/PushoverHandlerTest.php
- tests/Monolog/Handler/RollbarHandlerTest.php
- tests/Monolog/Handler/RotatingFileHandlerTest.php
- tests/Monolog/Handler/SlackHandlerTest.php
- tests/Monolog/Handler/SocketHandlerTest.php
- tests/Monolog/Handler/StreamHandlerTest.php
- tests/Monolog/Handler/SwiftMailerHandlerTest.php
- tests/Monolog/Handler/SymfonyMailerHandlerTest.php
- tests/Monolog/Handler/ZendMonitorHandlerTest.php
- tests/Monolog/PsrLogCompatTest.php
- tests/Monolog/SignalHandlerTest.php
I'd be happy to have help/guidance here cc @ezimuel 
Any other changes required? 
#1660 mentioned something about `_type` failing, and I'm not sure what it's about as I have close to no experience with elastic search myself.
> ElasticSearch v8 support

- src/Monolog/Formatter/GelfMessageFormatter.php
- tests/Monolog/Formatter/GelfMessageFormatterTest.php
- tests/Monolog/Handler/GelfHandlerTest.php
- the getter/setter methods for file, level and facility are deprecated in gelf v1.1
- add those fields as additional instead, as suggested in the gelf spec (https://docs.graylog.org/v1/docs/gelf#gelf-payload-specification)
- update tests to reflect changes
(continuation of #1658)
> replace deprecated method calls in GelfMessageFormatter

- src/Monolog/Formatter/LineFormatter.php
- tests/Monolog/Formatter/LineFormatterTest.php
This PR includes the hability to filter or parse the exception `trace` to avoid or customize every trace line.
For example, I want to avoid to log Laravel Framework lines, except if is the first one:
```php
$formatter = new LineFormatter(null, 'Y-m-d H:i:s', true, true);
$formatter->includeStacktraces(true, function ($line) {
if (!str_contains($line, '/vendor/laravel/') || str_starts_with($line, '#0 ')) {
return $line;
}
});
```
Without the parser, I get the log as:
```
[2022-05-06 11:47:16] local.ERROR: Call to undefined method App\Domains\Product\Model\Product::orderyCreatedAt() {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method App\\Domains\\Product\\Model\\Product::orderyCreatedAt() at …
```
> [2.X] Allow stacktraces parser on LineFormatter

- src/Monolog/Handler/MandrillHandler.php
swiftmailer/swiftmailer ^6.0 is officialy supported and setDate signature has changed in it
> Fix MandrillHandler for swiftmailer >= 6.0.0

- src/Monolog/Handler/RotatingFileHandler.php
- tests/Monolog/Handler/RotatingFileHandlerTest.php
Setting filename format with slashes
```php
$handler = new RotatingFileHandler('path/to/save/sample.log', 2);
$handler->setFilenameFormat('{date}/{filename}', 'Y/m/d');
```
`path/to/save/[year]/[month]/[day]/sample.log`
> RotatingFileHandler to maintain the correct maximum number files when using folder by date

- src/Monolog/Formatter/GoogleCloudLoggingFormatter.php
- tests/Monolog/Formatter/GoogleCloudLoggingFormatterTest.php
Google Cloud Logging doesn't show the correct level log when using JsonFormatter, making observability a bit trickier. This applies minor tweaks to the default format, allowing log entries to be properly represented.
There are alternative packages to this but they add fields that aren't strictly required - also performing `debug_backtrace()` calls that are usually not desired when in production mode.
> Add basic support to Google Cloud Logging format

- src/Monolog/Formatter/GoogleCloudLoggingFormatter.php
- tests/Monolog/Formatter/GoogleCloudLoggingFormatterTest.php
Google Cloud Logging doesn't show the correct level log when using JsonFormatter, making observability a bit trickier. This applies minor tweaks to the default format, allowing log entries to be properly represented.
There are alternative packages to this but they add fields that aren't strictly required - also performing `debug_backtrace()` calls that are usually not desired when in production mode.
This is a backport of https://github.com/Seldaek/monolog/pull/1690
> Add basic support to Google Cloud Logging format (v2)

- src/Monolog/Handler/ChromePHPHandler.php
- src/Monolog/Utils.php
- tests/Monolog/Handler/ChromePHPHandlerTest.php
> Fix utf8_encode deprecation

- src/Monolog/Handler/BrowserConsoleHandler.php
Instead of using `console.log` for all log levels, it uses `debug`, `info`, `warn` and `error` methods depending on the log level.
This makes filtering logs easier in the browser console and highlights error level messages.
> Update BrowserConsoleHandler console output method

- CHANGELOG.md
- doc/02-handlers-formatters-processors.md
- src/Monolog/Processor/ClosureContextProcessor.php
- tests/Monolog/Processor/ClosureContextProcessorTest.php
Hi! That processor generates a context by a closure if the closure is set as the only value in the context.
I use it a lot to reduce performance impact by debug code.
e.g.
```php
function register () {
// this:
$log->debug('User registration in progress: {uuid}, {date}, {profiled}, {more}', [
// expensive context generation !!!
]);
// changes to:
$log->debug('User registration in progress: {uuid}, {date}, {profiled}, {more}', [fn() => [
// expensive context generation in closure will run only if debug level is set
]]);
$log->info('User {name} registered.' ['name' => $user->name]);
}
```
> Add ClosureContextProcessor

- src/Monolog/Formatter/GoogleCloudLoggingFormatter.php
- tests/Monolog/Formatter/GoogleCloudLoggingFormatterTest.php
Fixes https://github.com/Seldaek/monolog/issues/1754
We introduced the formatter using the incorrect field, which was making GCP not to extract the correct value from the payload.
This uses the field that actually maps to the expected format.
More info: https://cloud.google.com/logging/docs/structured-logging
> Fix date/time field for GCP logging

- src/Monolog/Logger.php
- tests/Monolog/LoggerTest.php
We keep a separate depth count per fiber.
Fixes #1752.
> Fix cycle detection within fibers

- src/Monolog/Handler/ElasticsearchHandler.php
- tests/Monolog/Handler/ElasticsearchHandlerTest.php
When pushing logs to a [data stream](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html) in Elasticsearch, the [op_type](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#docs-index-api-op_type) must be set to "create". By default, the ElasticsearchHandler uses the "index" op_type. I have added an option to the ElasticsearchHandler so that you can specify the op_type to use and therefore enable the ability to push logs into an Elasticsearch data stream.
The default selection still is set to "index" so no behavior will change unless you specifically include the "op_type" option when creating the client.
- Elasticsearch Documentation: [Add documents to a data stream](https://www.elastic.co/guide/en/elasticsearch/reference/current/ …
> Add an option to set the op_type for the ElasticsearchHandler

- .github/workflows/continuous-integration.yml
- .github/workflows/lint.yml
- .github/workflows/phpstan.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- .github/workflows/continuous-integration.yml
- .github/workflows/lint.yml
- .github/workflows/phpstan.yml
This PR solves the warning show at https://github.com/Seldaek/monolog/actions/runs/4385271671 
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> ci: Update to use GitHub Actions V3

- composer.json
Version 2 is stable and released now
https://github.com/bzikarsky/gelf-php/releases
> chore: use stable version of graylog2/gelf-php

- src/Monolog/Attribute/AsMonologProcessor.php
- tests/Monolog/Attribute/AsMonologProcessorTest.php
As suggested in the [Monolog-bundle](https://github.com/symfony/monolog-bundle/pull/455#discussion_r1143066893).
So that the order in which the processors are used by monolog can be determined.
> Add support for priority to Monolog processors

- src/Monolog/Handler/TelegramBotHandler.php
- tests/Monolog/Handler/TelegramBotHandlerTest.php
The telegram API support sending message to a specific topic for supergroups.
This `message_thread_id` parameter wasn't added on #1451 because it didn't exist by that time.
https://core.telegram.org/bots/api#sendmessage
> TelegramBotHandler topics support

- src/Monolog/Handler/RotatingFileHandler.php
The function of adding yearly or monthly rotation log file. Although there are relevant definitions in the code before, it has not really supported it.
> Add support yearly or monthly rotation log file

- src/Monolog/Attribute/WithMonologChannel.php
- tests/Monolog/Attribute/WithMonologChannelTest.php
This attribute is meant to be used by frameworks / integrations to choose which logger instance to inject in a class when they manage several channels, if they decide to use it.
This attribute will have no effect in Monolog itself as the wiring of the logger in other classes is not managed by Monolog.
> Add a WithMonologChannel attribute

- src/Monolog/Test/TestCase.php
This method is not yet reported by PHPUnit as a warning. But as it has the `@deprecated` annotation, it gets reported by the phpstan setup as it detects usages of deprecated APIs.
> Remove usage of soft-deprecated PHPUnit API

- .github/workflows/continuous-integration.yml
- .github/workflows/lint.yml
- .github/workflows/phpstan.yml
Update actions/checkout to v4
[actions/checkout/releases/v4.0.0](https://github.com/actions/checkout/releases/tag/v4.0.0)
> Update actions/checkout to v4

- src/Monolog/Handler/LogglyHandler.php
"The issue was explained quite nicely, and I have created the PR."
Fixes #1838
> Loggly handler loglevel comparison statement fixed  Issue: #1838

- src/Monolog/Handler/TelegramBotHandler.php
These instructions clarify the details of setting Telegram chat ID for different types of chats.
https://github.com/Seldaek/monolog/issues/1787
> Clarified instructions about chat ID for Telegram

- src/Monolog/Formatter/LineFormatter.php
- tests/Monolog/Formatter/LineFormatterTest.php
When I pass in an indexed array or a multi-dimensional array, `allowInlineLineBreaks` is not working!
I think this revision is useful.
```php
$log->info('Testing new lines in log context.', ["This\nhas\nNew Lines."]);
// before
// local.INFO: Testing new lines in log context. ["This\nhas\nNew Lines."] 
// after
// local.INFO: Testing new lines in log context. ["This
// has
// New Lines."] 
```
> Add support for LineFormatter replace inline linebreaks in indexed arrays data

- src/Monolog/Formatter/MongoDBFormatter.php
- tests/Monolog/Handler/MongoDBHandlerTest.php
Without this patch, `MongoDBHandlerTest::testHandleWithLibraryClient()` test fails
---
**⚠ I'm really not sure about this PR!**
> Skip mongodb extension if extension is not installed

- src/Monolog/Handler/FallbackGroupHandler.php
- src/Monolog/Handler/GroupHandler.php
- src/Monolog/Handler/WhatFailureGroupHandler.php
- src/Monolog/Logger.php
- tests/Monolog/Handler/ExceptionTestHandler.php
- tests/Monolog/Handler/FallbackGroupHandlerTest.php
- tests/Monolog/Handler/GroupHandlerTest.php
- tests/Monolog/Handler/WhatFailureGroupHandlerTest.php
- tests/Monolog/LoggerTest.php
Context:
- Let's say i have 3 handlers attached to monolog logger: file handler, slack handler, elastic search handler.
- Note that each handler can push its own processor, which can alter the LogRecord entity.
- On the elastic search handler, we need extra info, so push a processor to add them,  (stupid example: `$logRecord->extra['new_entry_just_for_elastic_search'] = 'stuff';`
- This "extra" data i also available for file handler and slack handler.
- Basically i will get in slack handler and file handler, this extra that was supposed to be only for elastic search handler.
Why this is happening?
- LogRecord is passed by reference, to each handler.
- LogRecord accepts to alter data from `extra`, so if one handlers manages to alter this object, rest of remaining handlers, will use the …
> Fix LogRecord "extra" data leaking between handlers

- src/Monolog/Handler/FilterHandler.php
- src/Monolog/Handler/FingersCrossedHandler.php
- src/Monolog/Handler/SamplingHandler.php
- src/Monolog/Handler/Slack/SlackRecord.php
- src/Monolog/Handler/TelegramBotHandler.php
- src/Monolog/Logger.php
- src/Monolog/Processor/WebProcessor.php
not doing this will be deprecated in PHP 8.4 (see e.g. https://github.com/symfony/symfony/actions/runs/8400245907/job/23007289359#step:7:140)
> explicitly mark nullable parameters as nullable

- src/Monolog/Formatter/GoogleCloudLoggingFormatter.php
Most (if not all) other classes in the project are not marked as final.
Although it's possible to extend the functionality of this class by using composition, it goes against how the rest of the library works for no apparent reason.
In my use case, I was trying to add a field linking the log entry to a request [as described in the Cloud Logging documentation](https://cloud.google.com/run/docs/logging#correlate-logs).
> Remove `final` from class declaration

- src/Monolog/Formatter/NormalizerFormatter.php
- tests/Monolog/Formatter/NormalizerFormatterTest.php
HI @Seldaek
This is an improvement of https://github.com/Seldaek/monolog/issues/673
When a __toString method call throws an exception (which should occurs as few as possible), the Normalizer is throwing an exception too. I believe this behavior is wrong because:
- I cannot say monolog to prefer the default behavior over the __toString method
- If I wouldn't have a __toString method, it would have work correctly
Also, I have the following situation when using DoctrineFixtureBundle:
- I wrote a bug in my fixtures
- An exception is thrown
- During this process, monolog try to do some logs
- For the logs, he look for FooObject::__toString() method
- This method return the name of the FooObject which require a database request (because of doctrine lazy proxy)
- The entity is not found in …
> [NormalizerFormatter] Avoid throwing an exception when the toString call fails

- .github/workflows/phpstan.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> Use GITHUB_OUTPUT envvar instead of set-output command as the latter is deprecated

- src/Monolog/Handler/PsrHandler.php
- tests/Monolog/Handler/PsrHandlerTest.php
Currently PsrHandler pass only context, but missing all extra data. This PR adds option to merge this two arrays and pass as context into psr logger.
> Include extra in context in PsrHandler

- src/Monolog/Handler/AmqpHandler.php
This is just an idea how to make the GelfMessageFormatter and AmqpHandler compatible (again).
> Convert GelfMessage into string required by createAmqpMessage

- src/Monolog/Handler/DeduplicationHandler.php
This is a draft to solve #1878 
Feel free to comment on the changes I made!
Although the tests ran through without modification, this change is not backwards compatible when you look at it closely, because it changes the signature of several methods (changed visibility from private to protected, add parameters etc.).
> [#1878] User definable duplication for DeduplicationHandler

- src/Monolog/Formatter/LineFormatter.php
**OPT-IN**, This makes smaller logs entries, it is easy to read too
**Before**
```
Error at /var/www/vhosts/myvhost.com/app/Models/MyModel.php:165)
[stacktrace]
/var/www/vhosts/myvhost.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1475)
/var/www/vhosts/myvhost.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1218)
/var/www/vhosts/myvhost.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1199)
```
**After**
```php
$formatter->basePath('/var/www/vhosts/myvhost.com'); //laravel has base_path()
```
```
Error at app/Models/MyModel.php:165)
[stacktrace]
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1475)
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1218) …
```
> Remove base path on LineFormatter

- tests/Monolog/Processor/IntrospectionProcessorTest.php
Three tests in IntrospectionProcessorTest (testLevelTooLow, testLevelEqual, testLevelHigher) aren't actually testing anything. Because `$expected = $input` is a reference, the changes made to `$expected['extra']` are made to $input and carried forward to $actual. You can demonstrate this by adding a `return $record` at the immediate start of `InstrospectionProcessor::__invoke` -- the tests still pass despite bypassing all the code.
Fixes #1895
> Fix IntrospectionProcessor tests resulting in false positives

- src/Monolog/LogRecord.php
since $record['formatted'] is a legal syntax, it should not be flagged by static analysis tools like phpstan
> add formatted key in ArrayAccess for LogRecord

- src/Monolog/Handler/RedisHandler.php
The third argument to RedisHandler is a log level, not `prod` string.
> Update example in RedisHandler

- src/Monolog/Handler/PHPConsoleHandler.php
Google URL Shortener links will no longer be available: https://developers.googleblog.com/en/google-url-shortener-links-will-no-longer-be-available/
> Replace goo.gl URL

- src/Monolog/Handler/FingersCrossedHandler.php
- src/Monolog/Handler/TelegramBotHandler.php
Add `null` type hint for nullable method parameters.
See also https://wiki.php.net/rfc/deprecate-implicitly-nullable-types
> Fix PHP 8.4 deprecation notices

- src/Monolog/Processor/IntrospectionProcessor.php
Currently is very hard to make IntrospectionProcessor extendable from custom implementation (we have custom features implemented for Magento logging).
> Make IntrospectionProcessor extendable

- src/Monolog/Handler/ProcessHandler.php
In our application, any request has always been blocked for 1 second and made it significantly slower. Rather than needing to overwrite almost the entire class with a custom implementation, it would be nice to have this timeout configurable.
> ProcessHandler: Make timeout of `stream_select()` configurable

- src/Monolog/Formatter/ElasticaFormatter.php
- src/Monolog/Formatter/ElasticsearchFormatter.php
- src/Monolog/Formatter/FluentdFormatter.php
- src/Monolog/Formatter/HtmlFormatter.php
- src/Monolog/Formatter/JsonFormatter.php
- src/Monolog/Formatter/LineFormatter.php
- src/Monolog/Formatter/LogstashFormatter.php
- src/Monolog/Formatter/NormalizerFormatter.php
- src/Monolog/Formatter/WildfireFormatter.php
- src/Monolog/Handler/ChromePHPHandler.php
> Remove pointless json_encode availability checks

- README.md
The suggested library (https://github.com/Flynsarmy/Slim-Monolog) only supports Slim 2, which has not been maintained for a long time. Monolog can be integrated with Slim v4 directly, without the need for any additional libraries.
> Remove Slim framework integration suggestion

- src/Monolog/Handler/StreamHandler.php
- tests/Monolog/Handler/StreamHandlerTest.php
Fixes #1862, fixes #1860, fixes #1634
> Close and reopen file handles if a write fails

- CHANGELOG.md
- UPGRADE.md
- doc/message-structure.md
- src/Monolog/DateTimeImmutable.php
- src/Monolog/Formatter/NormalizerFormatter.php
- src/Monolog/Handler/ChromePHPHandler.php
- src/Monolog/JsonSerializableDateTimeImmutable.php
- src/Monolog/Logger.php
- src/Monolog/Processor/PsrLogMessageProcessor.php
- src/Monolog/Test/TestCase.php
- tests/Monolog/Formatter/ScalarFormatterTest.php
- tests/Monolog/LoggerTest.php
> Deprecate DateTimeImmutable

- doc/02-handlers-formatters-processors.md
Minor fix in documentation where the url to php documentation website was broken
> Fix broken url

- src/Monolog/Level.php
Changes the `fromName` method to be case-insensitive for more flexible use.
> Add `strtolower` for `fromName` match statement

- src/Monolog/Handler/ErrorLogHandler.php
Introduced via f43e3d563776da6e696648025437ea0576dd1e9a
> Fix ErrorLogHandler type hint: $messageType accepts only SAPI and OS

- src/Monolog/Handler/NativeMailerHandler.php
- tests/Monolog/Handler/NativeMailerHandlerTest.php
The existing call to the global mail() function in NativeMailHandler::send() is replaced with a call to a protected method NativeMailHandler::mail() that takes the same parameters. The provided implementation of NativeMailHandler::mail() passes through to the global mail() function, leaving existing behavior completely unchanged.
This allows subclassing NativeMailHandler so that the call to mail() can be replaced in cases where additional processing needs to happen.
Tests are mostly updated to use this method to test sent messages, but one test is added to make sure that everything gets passed through intact in the default case.
I have run into a number of cases specific to FreeBSD 14+ where its new native mailer (dma) often rejects messages generated by Monolog. The added functionality …
> Add a mail() hook to NativeMailHandler.

- src/Monolog/Formatter/ElasticsearchFormatter.php
- tests/Monolog/Handler/ElasticaHandlerTest.php
- tests/Monolog/Handler/ElasticsearchHandlerTest.php
> Change datetime format from ISO 8601 to ATOM in ElasticsearchFormatter
